### ISSUE TITLE
Possible broken against Ubuntu 14.04

### ISSUE THREAD

**Issue by kimhaak** [muffycompo/radiusdesk-installer#11]
Hi

Thanks for the effort making this, appreciate it!

I am a newbie, but i think your script may be broken towards ubuntu. 

Tried an install, and got lots of errors. This was on a new machine.

What i have found is:

Freeradius filename is wrong. You download version 3, but try to untar version 2.
Libtalloc-dev was missing on my machine, so compile of Freeradius failed. 
Cakephp dir  is actually cakephp-master after unzip - this seems to break cakephp install.

I have tried to fix these things, and things seemed to go better. It is compiling FR now, but it is also giving some error messages on previous steps, but these looks related to already existing dirs, as i have run the script over and over again. (Maybe it should have a "clean" option for reinstall purposes?)

Anyway, i may not have pointed out all (or any) faults, but you might get an idea of what to check.

Regards

Kim

**Comment by muffycompo** [comment]
Thanks for raising this issue, will take some time out this weekend to fix the script and possibly workout a way to clean the installation when it fails.

**Comment by muffycompo** [comment]
I have push a new version of the installer, maybe if you still have the issue, you can try the new installer which now uses Ansible.
