### ISSUE TITLE
Script fails to work due to wrong filename passed to unzip

### ISSUE THREAD

**Issue by mdanh2002** [muffycompo/radiusdesk-installer#12]
The script is no longer working, possibly after the changes on 22 Sep with notes 'Removed cake version specific commands'. What this does is to remove specific version-references from functions.sh when unzipping file, e.g. in install_cakephp(), changed from cakephp-2.2.9.zip to cakephp.zip. However, the downloaded filename in rhel_centos_core.sh (and possibly the Ubuntu ones) was not changed - it still has the version number appended. This causes the unzip to fail and thus prevent the rest of the script from working.

**Comment by muffycompo** [comment]
Thanks for pointing that out, there is a rewrite coming along, not committed to version control yet, but will soon be available for testing. It should work with RHEL/CentOS 6-7, Debian and Ubuntu 12-15.

**Comment by muffycompo** [comment]
A new version has been uploaded, kindly test and send your feedback.
