### ISSUE TITLE
Wrong repo path to FreeRadius installer

### ISSUE THREAD

**Issue by mdanh2002** [muffycompo/radiusdesk-installer#13]
Additionally in functions.sh, function install_mao_repo() the path to http://www.maomuffy.com/freeradius/repo/maorepo-el6-x86_64.repo returns 404 and FreeRadius could not be installed. I believe simply removing all the add-repo nonsense and just perform a yum install would make the script work properly again

**Comment by muffycompo** [comment]
@mdanh2002 thanks for the Observation but as you may have seen, the script is broken and I have been working on an update. The reason for the custom repo was because of the version of FreeRADIUS with RAW support baked in.
