### ISSUE TITLE
Wrong version of ExtJS being used

### ISSUE THREAD

**Issue by mdanh2002** [muffycompo/radiusdesk-installer#14]
Well, I successfully modified the script and managed to let it install MySQL + Apache + FreeRadius without any error messages and thought that's it when I suddenly realized that the installed RadiusDesk application (http://localhost/rd) would not open and just hang at the RadiusDesk logo. After much debugging it turns out that the issue was due to the fact that the script installs the latest version of RadiusDesk from the trunk but uses ExtJS version 4.2.1. For the last few versions, RadiusDesk has been using ExtJS 6.0, and the old release which used ExtJS 4.2.1 was renamed as rd_legacy (see SVN branch http://svn.code.sf.net/p/radiusdesk/code/trunk/). Both ExtJS releases are also available on the RadiusDesk SVN for download (http://svn.code.sf.net/p/radiusdesk/code/extjs/). I fixed the issue by manually downloading the correct versions of ExtJS and put in /var/www/html after the install is completed.

**Comment by muffycompo** [comment]
Thanks again for the updates, could you be so kind to submit a pull request
with your changes to help those still using this version of the script.
Regards!

On Tue, Dec 15, 2015 at 1:33 AM, mdanh2002 <notifications@github.com> wrote:

> Well, I successfully modified the script and managed to let it install
> MySQL + Apache + FreeRadius without any issues and thought that's it when I
> suddenly realized that the installed RadiusDesk application (
> http://localhost/rd) would not open and just hang at the RadiusDesk logo
> After much debugging it turns out that the issue was due to the fact that
> the script installs the latest version of RadiusDesk from the trunk as well
> as ExtJS 421 However, for the last few versions, RadiusDesk has been using
> ExtJS 60, and the old release which used ExtJS 421 was renamed as rd_legacy
> (see SVN branch http://svncodesfnet/p/radiusdesk/code/trunk/) Both ExtJS
> releases are also available on the RadiusDesj SVN for download (
> http://svncodesfnet/p/radiusdesk/code/extjs/) I fixed the issue by
> manually downloading the files and put in /var/www/html after the install
> is completed
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/muffycompo/radiusdesk-installer/issues/14>.
>



-- 
*Mfawa Alfred Onen*
System Administrator / GDG Lead, Bingham University
Department of Computer Science,
Bingham University.

E-Mail: muffycompoqm@gmail.com
Phone1: +234 805 944 3154
Phone2: +234 803 079 6088
Twitter: @muffycompo <https://twitter.com/muffycompo>
Google+: https://plus.google.com/+MfawaAlfredOnen
