### ISSUE TITLE
Improve debug log and status checking during installation

### ISSUE THREAD

**Issue by mdanh2002** [muffycompo/radiusdesk-installer#15]
I checked the code and notice that most installation steps in functions.sh ignore the command output (just redirect them to >dev>null). This is pretty a bad idea because you won't know whether the command succeeds or not and if not, what the error messages are. I believe all output needs to be redirected to a log file for debugging purposes.

Secondly, the last step of the installation (Checking if services are operational) calls start_service and restart_service for the nodejs, apache/nginx and radiusd service but does not attempt to check if the services have been successfully restarted. In my case, FreeRadius could not be installed due to a 404 returned from the maomuffy repo but the script still says that the installation is successful!

I believe the correct way is to check the service command return code, or at least use something like "service radiusd status" after "service radiusd start" without output redirection and let the user see whether the service has been installed successfully. 

Lastly the script should also check whether CakePHP and NodeJS have been successfully installed by wgetting http://localhost:8000/socket.io/socket.io.js and http://localhost/cake2/rd_cake/phrase_values/get_language_strings.json?_dc=1355816922405&language= as per the instructions from http://www.radiusdesk.com/getting_started/install after installation. If successful, the first URL will return the NodeJS socket javascript code whereas the second one will return some JSON output, which is being used for RadiusDesk localization. These two URLs are critical for the operation of RadiusDesk.

And for those who encounter similar problems of RadiusDesk not loaded after installation, first check the browser console log for possible error messages. Next, check the CakePHP error log at /var/www/html/cake2/rd_cake/tmp/. If there are things like "JSON strings could not be decoded" inside the logs and the RadiusDesk dialog header is cut-off or otherwise non-functional, one possible reason is the unexpected output of debug messages (warnings/errors) from the PHP engine and CakePHP. Check /etc/php.ini and set display_errors to off, then edit app/config/core.php inside the RadiusDesk CakePHP application change Configure::write() to disable the logging totally. This is because the warnings/debug messages output may disrupt the format of the JSON data stream and cause the RadiusDesk app to fail.

**Comment by DragonStuff** [comment]
Hey mdanh2002,
Could you please share your fixed script with us? I have been experiencing a heap of issues trying to get this script working as it doesn't use the correct version of ExtJS, and fails on the FreeRADIUS install. :(

Maintainer: Please fix?

Thanks!

**Comment by muffycompo** [comment]
I just push a new version of the installer which now uses Ansible, Kindly try it and send your feedback. Also note that it is still beta code so...http://muffycompo.github.io/radiusdesk-installer/
