### ISSUE TITLE
Installation not working on ubuntu 14.04.3 on digital ocean

### ISSUE THREAD

**Issue by willmkt** [muffycompo/radiusdesk-installer#16]
I get all of these errors:

10. Installing CakePHP
mv: cannot stat ‘/tmp/radiusdesk/cakephp’: No such file or directory

=============================================================
11. Installing RADIUSdesk
cp: cannot create directory ‘/usr/share/nginx/html/cake2/’: File exists
cp: cannot stat ‘/usr/share/nginx/html/cake2/rd_cake/Setup/Node.js/nodejs-socket-io’: No such file or directory

=============================================================
12. Installing Sencha ExtJS

=============================================================
13. Installing Cron Script for RADIUSdesk
cp: cannot stat ‘/usr/share/nginx/html/cake2/rd_cake/Setup/Cron/rd’: No such file or directory
grep: /usr/share/nginx/html/cake2: No such file or directory
sed: no input files
sed: can't read /etc/cron.d/rd: No such file or directory

=============================================================
14. Updating RADIUSdesk Paths for Ubuntu/Debian compatibility
sed: can't read /usr/share/nginx/html/cake2/rd_cake/Config/RadiusDesk.php: No such file or directory

=============================================================
15. Installing FreeRADIUS
sed: can't read /usr/share/nginx/html/cake2/rd_cake/Setup/Scripts/radscenario.pl: No such file or directory
sed: can't read /usr/share/nginx/html/cake2/rd_cake/Setup/Db/rd.sql: No such file or directory
tar (child): freeradius-server-2.2.0.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
includes/functions.sh: line 327: cd: freeradius-server*/: No such file or directory
includes/functions.sh: line 328: /usr/share/nginx/html/cake2/rd_cake/Setup/Radius/rlm_raw_patch: No such file or directory
includes/functions.sh: line 329: src/modules/stable: No such file or directory
cp: cannot stat ‘/usr/local/sbin/rc.radiusd’: No such file or directory
cp: cannot stat ‘/usr/share/nginx/html/cake2/rd_cake/Setup/Radius/checkrad’: No such file or directory
mv: cannot stat ‘/usr/local/etc/raddb/’: No such file or directory
tar (child): /usr/share/nginx/html/cake2/rd_cake/Setup/Radius/raddb_rd.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
sed: can't read /usr/local/etc/raddb/radiusd.conf: No such file or directory
sed: can't read /usr/local/etc/raddb/clients.conf: No such file or directory
sed: can't read /usr/local/etc/raddb/clients.conf: No such file or directory
ln: failed to create symbolic link ‘/usr/local/etc/raddb/sites-enabled/dynamic-clients’: No such file or directory
cp: cannot create regular file ‘/usr/local/etc/raddb/sites-enabled/dynamic-clients’: No such file or directory
includes/functions.sh: line 352: /usr/local/etc/raddb/modules/raw: No such file or directory
sed: can't read /usr/share/nginx/html/cake2/rd_cake/Setup/Node.js/Logfile.node.js: No such file or directory
sed: can't read /usr/share/nginx/html/cake2/rd_cake/Setup/Node.js/Logfile.node.js: No such file or directory
sed: can't read /usr/share/nginx/html/cake2/rd_cake/Setup/Node.js/Logfile.node.js: No such file or directory
sed: can't read /usr/share/nginx/html/cake2/rd_cake/Setup/Node.js/Logfile.node.js: No such file or directory
sed: can't read /usr/local/etc/raddb/sql.conf: No such file or directory
sed: can't read /usr/local/etc/raddb/sql.conf: No such file or directory
sed: can't read /usr/local/etc/raddb/sql.conf: No such file or directory
sed: can't read /usr/local/etc/raddb/sql.conf: No such file or directory
sed: can't read /usr/local/etc/raddb/rlm_perl_modules/SQLConnector.pm: No such file or directory
sed: can't read /usr/local/etc/raddb/rlm_perl_modules/SQLConnector.pm: No such file or directory
sed: can't read /usr/local/etc/raddb/rlm_perl_modules/SQLConnector.pm: No such file or directory
sed: can't read /usr/local/etc/raddb/rlm_perl_modules/SQLConnector.pm: No such file or directory
sed: can't read /usr/share/nginx/html/cake2/rd_cake/Config/database.php: No such file or directory
sed: can't read /usr/share/nginx/html/cake2/rd_cake/Config/database.php: No such file or directory
sed: can't read /usr/share/nginx/html/cake2/rd_cake/Config/database.php: No such file or directory
sed: can't read /usr/share/nginx/html/cake2/rd_cake/Config/database.php: No such file or directory

=============================================================
16. Installing Database Schema for RADIUSdesk
includes/functions.sh: line 280: /usr/share/nginx/html/cake2/rd_cake/Setup/Db/rd.sql: No such file or directory
chmod: cannot access ‘/usr/local/sbin/checkrad’: No such file or directory
chmod: cannot access ‘/usr/local/etc/raddb/dictionary’: No such file or directory
chmod: cannot access ‘/usr/share/nginx/html/cake2/rd_cake/Setup/Scripts/*.pl’: No such file or directory
chmod: cannot access ‘/etc/init.d/nodejs-socket-io’: No such file or directory

=============================================================
17. Installing NodeJS
sed: can't read /etc/init.d/nodejs-socket-io: No such file or directory
sed: can't read /etc/init.d/nodejs-socket-io: No such file or directory
sed: can't read /etc/init.d/nodejs-socket-io: No such file or directory

=============================================================
18. Checking if services are fully Operational

===========================================================================
INSTALLATION COMPLETED SUCCESSFULLY!!!

Is the script broken??

Thanks

**Comment by muffycompo** [comment]
Hello, I am working on a more updated script as this one is broken with the
recent changes in Radiusdesk code base.

**Comment by willmkt** [comment]
Any upadate when it will be ready?

Thanks.

**Comment by muffycompo** [comment]
I have just push another version of the installer this time using Ansible, try it and kindly leave your feedback as it is still beta code.
