### ISSUE TITLE
Installer not passing "Configuring Nginx to use UNIX sockets (Ubuntu)" on fresh ubuntu 14.04

### ISSUE THREAD

**Issue by adrian-balcan-ygt** [muffycompo/radiusdesk-installer#17]
TASK: [radiusdesk | Configuring Nginx to use UNIX sockets (Ubuntu)] *********** 
fatal: [localhost] => {'msg': "One or more undefined variables: 'ansible_distribution_major_version' is undefined", 'failed': True}
fatal: [localhost] => {'msg': "One or more undefined variables: 'ansible_distribution_major_version' is undefined", 'failed': True}

FATAL: all hosts have already failed -- aborting

**Comment by muffycompo** [comment]
@adrian-balcan-ygt The error shows that it can't recognize the OS properly even though you indicated Ubuntu 14.04. What version of Ansible do you have installed on your control host/server?

**Comment by muffycompo** [comment]
@adrian-balcan-ygt any luck with fixing this issue?

**Comment by j0r1993** [comment]
i have fixed this issue updating ansible following this http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-ubuntu
