### ISSUE TITLE
Issue with SSH

### ISSUE THREAD

**Issue by akuchuterry** [muffycompo/radiusdesk-installer#19]
GATHERING FACTS ***************************************************************
fatal: [192.168.137.2] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue

TASK: [radiusdesk | Adding RadiusDesk Variables (Ubuntu)] *********************
FATAL: no hosts matched or all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/akuchu/rd-installer-ansible.retry

192.168.137.2              : ok=0    changed=0    unreachable=1    failed=0

  I get this error when i launch the installer..( 192.168.137.2 is the static IP address i have on my ubuntu server). But i added the IP to ssh as( ssh akuchu@192.168.137.2)   What might be the problem here?
 Thanks

**Comment by muffycompo** [comment]
The installer requires root privilege to run properly. Try using the root user and it should proceed accordingly.
