### ISSUE TITLE
Ansible fatal error

### ISSUE THREAD

**Issue by akuchuterry** [muffycompo/radiusdesk-installer#20]
fatal: [localhost] => {'msg': "One or more undefined variables: 'ansible_distribution_major_version' is undefined", 'failed': True}
fatal: [localhost] => {'msg': "One or more undefined variables: 'ansible_distribution_major_version' is undefined", 'failed': True}

FATAL: all hosts have already failed -- aborting. 
Please what do i do?
Thanks

**Comment by muffycompo** [comment]
Looks like you have not upgraded your version of ansibkr as per the installation guide https://github.com/muffycompo/radiusdesk-installer/blob/master/README.md#2-install-ansible-19
