### ISSUE TITLE
Coovachilli support

### ISSUE THREAD

**Issue by akuchuterry** [muffycompo/radiusdesk-installer#21]
Hello Mr. Muffy/Team
i have his scenario at hand and i need help from your development team.

I have an internet IP from my ISP as : 197.210.203.2  255.255.255.252.  I want to use coovachilli as my captive portal instead of a Mikrotik router.  I have successfully installed radiusdesk on my server ( ubuntu server 14.04 64bits),  and i have also installed coovachilli 1.3.0 on the same server. My internet is on eth0 , and i want to use eth1 for the hotspot. The truth is am confused on the steps to take. Please if you can help me outline all the steps to take inorder to run coovachilli on the server. 
Thanks for all the Support. God Bless! 

 I used to chat you on whatsapp before, but i lost your contact. my number is: +2348162661972 if you can chat me too. Thanks again.

**Comment by muffycompo** [comment]
Hello Terry, I think you should details this for me in an email: muffycompoqm[at]gmail[dot]com

**Comment by akuchuterry** [comment]
Hello Mr. Muffy/Team
i have his scenario at hand and i need help from your development team.

I have an internet IP from my ISP as : 197.210.203.2,
Gateway:197.210.203.1, Subnet:  255.255.255.252.

I want to use Coovachilli as my captive portal( where users will
authenticate with a username and password ) instead of a Mikrotik router.

I have successfully installed radiusdesk using your installer on github on
my server ( ubuntu server 14.04 64bits).

I have also installed Coovachilli 1.3.0 on the same server.

My internet  interface on the server is on *eth0* , and i want to use *eth1*
for the hotspot.

The truth is am confused on the steps to continue in configuring the
Coovachilli to work with the radiusdesk. Please if you can help me outline
all the steps or tutorials to take inorder to run coovachilli successfully
with radiusdesk on the server. I have gone through a video tutorial you did
sometime but it didn't help me.
I really appreciate your time and thanks for all the Support. God Bless!


Secondly i have also gone through  a project you did on ais_portal in 2013
on github: ( https://github.com/muffycompo/ais_portal).

I downloaded the zip file and put on my wamp server. But when i run the url
on the browser, it simple just list out the application file on my browser.
It means there is no index.php. What do you say??.

Thanks

On Tue, Mar 29, 2016 at 1:32 AM, Mfawa Alfred Onen <notifications@github.com

**Comment by akuchuterry** [comment]
Hello Mr. muffy,
  Hope your day is fine? I hope what i explained above is explicit for you.
I am patiently waiting on your response.
Thanks

**Comment by muffycompo** [comment]
Hello Terry, the installer also allows you t setup CoovaChilli. Watch the Walk through Video I made and towards the end, I pointed out how to enable CoovaChilli support in the roles variable file. Let me know when you've checked it out so that we can proceed from there.

**Comment by akuchuterry** [comment]
Hello Mr. Muffy, I have enabled the coovachilli support. Here is a
screenshot.
Thanks
[image: Inline image 1]

**Comment by iberrywifi** [comment]
Muffy i installed the radiusdesk from ur installer guide line. Unable to get dynamic dns working with mikrotik. It doesnt detect the mikrotik nas in dynamic dns. Thanks

**Comment by iberrywifi** [comment]
My email is admin@ibudha.com and rogers3b2@gmail.com I can give u the access if u want. thanks
