### ISSUE TITLE
Install Works, but I can't log in.

### ISSUE THREAD

**Issue by stevenmcastano** [muffycompo/radiusdesk-installer#22]
It looks like the installed did everything it needed to, but I wasn't able to log into afterwards with the default login and password. I click "OK" and I see the HTTP POST come in, but then nothing happens.

What am I missing?

**Comment by muffycompo** [comment]
Could you tell us what OS type and version you are running?

**Comment by stevenmcastano** [comment]
It’s Ubuntu Linux 14.04.4 LTS.

I ran the scripts again on 14.04.3 LTS and it worked great though!

**Comment by muffycompo** [comment]
Okay, thanks for the feedback. Closing the issue now.
