### ISSUE TITLE
install vixie-cron will be failed in CentOS 7

### ISSUE THREAD

**Issue by Halry** [muffycompo/radiusdesk-installer#23]
TASK [radiusdesk : Installing RadiusDesk packages (RHEL/CentOS 6.x/7.x)] *******
ok: [192.168.1.101] => (item=[u'php-fpm', u'php-pear', u'php-gd', u'php-common', u'php-cli', u'php-mysql', u'php-xcache', u'mysql-server', u'mysql', u'subversion', u'git', u'vixie-cron', u'mailx', u'python', u'MySQL-python', u'perl', u'unixODBC', u'postgresql', u'openldap', u'libtool-ltdl', u'gcc-c++', u'gcc', u'make', u'unzip', u'tar'])
	to retry, use: --limit @/root/radiusdesk-installer/rd-installer-ansible.retry

PLAY RECAP *********************************************************************
192.168.1.101              : ok=6    changed=1    unreachable=0    failed=1   

remove vixie-cron in vars will fix it.

**Comment by muffycompo** [comment]
Thanks @Halry, at the moment, CentOS 7 is not fully supported. There is work going on to make it fully compatible and support SystemD. It currently works well with CentOS/RHEL 6.x and Ubuntu 14.04/15.04/15.10
