### ISSUE TITLE
The installer is finished.But can't login.

### ISSUE THREAD

**Issue by Halry** [muffycompo/radiusdesk-installer#24]
The OS is CentOS 7
It shows:Failure Not Defined.
It seems it can't connect to database but honesty I don't know where it goes wrong.

**Comment by muffycompo** [comment]
There is no full support for CentOS 7 yet but it is on the way.

**Comment by Halry** [comment]
After change timezone and change the php-fpm socks to the ip.Now I can login.But freeradius won't work.I have to use the offical vm image now.'(But anyway,thanks for your hard work.

**Comment by stan-thomas** [comment]
After running the installer I too can't seem to get any login page on Centos 6.8. All related services seem to be running without any issues. Which file did you change?

**Comment by muffycompo** [comment]
@stan-thomas,  just tried replicating the error but worked for me. I setup a new Digital Ocean Server and ran the installer. Couple of Quick tips: 1) Try rebooting the server 2) Check Nginx Log files and see if anything interesting shows up.

**Comment by stan-thomas** [comment]
Hi Muffy,

No errors in the log files. The server is refusing connections over port 80. But "elinks http://localhost" shows me the default nginx page. I allowed port 80 using iptables. Still no luck.

**Comment by muffycompo** [comment]
Do you have SELinux enabled? It is strange really...could you provide teamviewer access or SSH so that I can help look around as well.

**Comment by stan-thomas** [comment]
"iptables --flush" sorted this.

**Comment by muffycompo** [comment]
Thanks for the feedback @stan-thomas. Will try allowing the script to flush iptables in an upcoming update...

**Comment by muffycompo** [comment]
Since we don't want the user to flush his existing rules (if any), we let them flush their firewall rules and don't make the installer handle that.
