### ISSUE TITLE
error certificate for apt.maomuffy.com

### ISSUE THREAD

**Issue by morlockes** [muffycompo/radiusdesk-installer#25]
Hello
 Im RADIUSDesk Installer – Ansible but not found the certificate. That´s the error.

The SO it´s Ubuntu 14.04.3 LTS

TASK [radiusdesk : Adding RadiusDesk MAO Apt Repository Key (Ubuntu)] **********
fatal: [x.x.x.x]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for apt.maomuffy.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}
        to retry, use: --limit @/home/radiusdesk-installer/rd-installer-ansible.retry

Best regards

**Comment by muffycompo** [comment]
Thanks for point this out @morlockes, the issue has been fixed and you can now clone a new copy setup your server.

**Comment by morlockes** [comment]
All it´s ok.
Thank you very much for your excellent work. :)
