### ISSUE TITLE
CentOS 6.8 freeradius won't start

### ISSUE THREAD

**Issue by stan-thomas** [muffycompo/radiusdesk-installer#27]
Hi Muffy,

Freeradius refuses to start "radiusd -X" gives this error and exits:

rlm_sql (sql): Driver rlm_sql_mysql (module rlm_sql_mysql) loaded and linked
rlm_sql (sql): Attempting to connect to rd@localhost:/rd
rlm_sql (sql): starting 0
rlm_sql (sql): Attempting to connect rlm_sql_mysql #0
rlm_sql_mysql: Starting connect to MySQL server for #0
rlm_sql (sql): Connected new DB handle, #0
rlm_sql (sql): starting 1
rlm_sql (sql): Attempting to connect rlm_sql_mysql #1
rlm_sql_mysql: Starting connect to MySQL server for #1
rlm_sql (sql): Connected new DB handle, #1
rlm_sql (sql): starting 2
rlm_sql (sql): Attempting to connect rlm_sql_mysql #2
rlm_sql_mysql: Starting connect to MySQL server for #2
rlm_sql (sql): Connected new DB handle, #2
rlm_sql (sql): starting 3
rlm_sql (sql): Attempting to connect rlm_sql_mysql #3
rlm_sql_mysql: Starting connect to MySQL server for #3
rlm_sql (sql): Connected new DB handle, #3
rlm_sql (sql): starting 4
rlm_sql (sql): Attempting to connect rlm_sql_mysql #4
rlm_sql_mysql: Starting connect to MySQL server for #4
rlm_sql (sql): Connected new DB handle, #4
rlm_sql (sql): Processing generate_sql_clients
rlm_sql (sql) in generate_sql_clients: query is SELECT id, nasname, shortname, type, secret, server FROM nas
rlm_sql (sql): Reserving sql socket id: 4
rlm_sql (sql): Read entry nasname=127.0.0.1,shortname=localhost,secret=greatsecret
rlm_sql (sql): Adding client 127.0.0.1 (localhost, server=<none>) to clients list
Failed to add duplicate client localhost
rlm_sql (sql): Released sql socket id: 4
rlm_sql (sql): Failed to add client 127.0.0.1 (localhost) to clients list.  Maybe there's a duplicate?
Failed to load clients from SQL.
rlm_sql (sql): Closing sqlsocket 4
rlm_sql (sql): Closing sqlsocket 3
rlm_sql (sql): Closing sqlsocket 2
rlm_sql (sql): Closing sqlsocket 1
rlm_sql (sql): Closing sqlsocket 0
/etc/raddb/sql.conf[22]: Instantiation failed for module "sql"
/etc/raddb/policy.conf[321]: Failed to find "sql" in the "modules" section.
/etc/raddb/policy.conf[321]: Failed to parse "sql" entry.
/etc/raddb/policy.conf[68]: Failed to parse "RADIUSdesk_user_check" entry.
/etc/raddb/policy.conf[389]: Failed to parse "RADIUSdesk_device_check" entry.
/etc/raddb/policy.conf[388]: Failed to parse "if" subsection.
/etc/raddb/sites-enabled/default[166]: Failed to parse "RADIUSdesk_main" entry.
/etc/raddb/sites-enabled/default[69]: Errors parsing authorize section.

Mysql is running fine, I can connect the "rd" database and view all tables too. Package "freeradius-mysql" is installed.

It looks like something to do with the freeradius config files.

**Comment by muffycompo** [comment]
Hmm...looks like there is a duplicate entry for the localhost/127.0.0.1 NAS client. Can I have access to your instance and check. Need to be sure...

**Comment by stan-thomas** [comment]
Sure you have the VPN access. The server is at 10.0.5.4/rd

**Comment by muffycompo** [comment]
As suspected, there was another entry for the localhost NAS client. Editing and commenting out the entry in /etc/raddb/clients.conf fixed it.

**Comment by stan-thomas** [comment]
Was it added by me? Now radiusd starts but there are some more errors.

Thu Aug 11 19:02:20 2016 : Info: rlm_sql_mysql: Starting connect to MySQL server for #4
Thu Aug 11 19:02:20 2016 : Info: rlm_sql (sql): Connected new DB handle, #4
Thu Aug 11 19:02:20 2016 : Info: Loaded virtual server <default>
Thu Aug 11 19:02:20 2016 : Info: Loaded virtual server dynamic_client_server
Thu Aug 11 19:02:20 2016 : Info: Loaded virtual server inner-tunnel
Thu Aug 11 19:02:20 2016 : Info: Ready to process requests.
Thu Aug 11 19:05:27 2016 : Info:  ... adding new socket command file /var/run/radiusd/radiusd.sock
Thu Aug 11 19:05:27 2016 : Info:  ... adding new socket command file /var/run/radiusd/radiusd.sock
Thu Aug 11 19:05:27 2016 : Info:  ... adding new socket command file /var/run/radiusd/radiusd.sock
Thu Aug 11 19:05:27 2016 : Info:  ... adding new socket command file /var/run/radiusd/radiusd.sock
Thu Aug 11 19:07:02 2016 : Error: Syntax error.  Expected condition at
Thu Aug 11 19:07:03 2016 : Error: Syntax error.  Expected condition at
Thu Aug 11 19:07:03 2016 : Error: Syntax error.  Expected condition at
Thu Aug 11 19:07:13 2016 : Error: Syntax error.  Expected condition at

Also trying to login with a user does not work. The login page just remains as is.

**Comment by muffycompo** [comment]
Make sure you set the correct radius secret in the NAS section of RD.

**Comment by stan-thomas** [comment]
NAS is localhost and the radius secret is correct. I get this error after saving changes in the default Dynamic Login Page.

**Comment by muffycompo** [comment]
Try the updated RADIUSDesk installer, that issue seems to have been fixed.
