### ISSUE TITLE
ubuntu 16.04 cannot open radiusdesk in browser after installation

### ISSUE THREAD

**Issue by Bratsk** [muffycompo/radiusdesk-installer#28]
Hey @muffycompo,
I try to install RADIUSdesk, to enable social login an a captive portal, on Ubuntu server 16.04 for a while now and I am still not successful. After a long search I found the latest installation guide with ansible, because it made the installation quite easy. 
I have installed till now
coovachilli for captive portal, freeradius, apache2, php, mysql, python 2.7,ansible 
I have followed your steps and the only difference till now was in the 
server file

```
[default]
192.168.1.221 ansible_connection=local ansible_ssh_user=root
```

- I removed the last 4 lines like you suggested in the tutorial video
- I set the IP address of my virtual machine since I can only access the server threw an external browser because the server itself does not have a browser. 
- I didn't changed anything in the rd-installer-ansible.yml file (perhaps I should but I have too few exprience)

The installation went threw with success. 
I can ping the server's 192.168.1.221 address from my windows machine on my computer as well as the virtual ubuntu client while the captive portal is open. 
When pasting the server's network address  `http://192.168.1.221/rd` get 404 error from the apache server. 
Have I done something wrong? Is there a collision between the apache server and RADIUSdesk? Is there a place where I can check if the network configuration is correct?
For any advice I will be thankfull because it takes hours to find any solution and I don't have any ideas any more. 
Thank You
Kamil

**Comment by muffycompo** [comment]
@Bratsk at the moment, the author of RADIUSDesk has confirmed that it does not support FR3 on Ubuntu 16+. I will recommend you use Ubuntu 14 instead.

**Comment by muffycompo** [comment]
Will Update the Installer as soon as upstream RADIUSDesk project works with Freeradius 3 on Ubuntu 16

**Comment by muffycompo** [comment]
Will Update the Installer as soon as upstream RADIUSDesk project works with Freeradius 3 on Ubuntu 16.
