### ISSUE TITLE
URL not found

### ISSUE THREAD

**Issue by stan-thomas** [muffycompo/radiusdesk-installer#29]
Hello Muffy,

I'm using an openwrt router for coova-chilli (as mentioned here http://www.radiusdesk.com/docuwiki/user_guide/chilli/coovaap but not using the same firmware). Everything seems to be working fine except when I try to browse after connect I get "Not found http://10.2.0.1/cake2/rd_cake/dynamic_details/chilli_browser_detect/?res=notyet&uamip=10.2.0.1&uamport=3990&challenge=352969b4b6e091f11604c45170608943&called=F4-F2-6D-46-1D-D0&mac=74-DE-2B-FD-0C-9F&ip=10.2.0.10&ssid=GreenEarth&nasid=CHLV&sessionid=57ce7bbc00000003&userurl=http%3a%2f%2frediff.com%2f&md=0A335098F8CA664399BACDCBFFA4D45B on this server"

I have another instance of coova-chilli running on a separate lan interface on the same radiusdesk installed system and it's working fine.

What would cause that error?

Thanks.

**Comment by muffycompo** [comment]
It's difficult to say, but are you running RD on a separate server? Does the IP address correspond to that of RD?

**Comment by stan-thomas** [comment]
Yes it is running on a separate server. This is the config

HS_LANIF=br-lan              # Subscriber Interface for client devices
HS_NETWORK=10.2.0.0        # HotSpot Network (must include HS_UAMLISTEN)
HS_NETMASK=255.255.0.0     # HotSpot Network Netmask
HS_UAMLISTEN=10.2.0.1      # HotSpot IP Address (on subscriber network)
HS_UAMPORT=3990            # HotSpot UAM Port (on subscriber network)
HS_UAMUIPORT=4990          # HotSpot UAM "UI" Port (on subscriber network, for embedded portal)
HS_NASID=CHLV
HS_RADIUS=192.168.60.29
HS_RADIUS2=192.168.60.29
HS_RADSECRET=testing123    # Set to be your RADIUS shared secret
HS_UAMSECRET=greatsecret     # Set to be your UAM secret
HS_UAMALIASNAME=chilli
HS_SSID="GreenEarth"
HS_NASIP=10.2.0.1    # To explicitly set NAS-IP-Address
HS_UAMSERVER=$HS_UAMLISTEN
HS_UAMFORMAT=http://\$HS_UAMLISTEN/cake2/rd_cake/dynamic_details/chilli_browser_detect/
HS_MACAUTH=on              # To turn on MAC Authentication
HS_TCP_PORTS="80 23 8000"
HS_MODE=hotspot
HS_TYPE=chillispot
HS_WWWDIR=/etc/chilli/www
HS_WWWBIN=/etc/chilli/wwwsh
HS_PROVIDER=Coova
HS_PROVIDER_LINK=http://www.coova.org/
HS_LOC_NAME="My HotSpot"           # WISPr Location Name and used in portal
HS_COAPORT=3799

**Comment by stan-thomas** [comment]
Oh yes I had to change the URL IP address to correspond to the server. It worked. Thanks Muffy.
