### ISSUE TITLE
Unable to add Profile Component to Profile

### ISSUE THREAD

**Issue by stan-thomas** [muffycompo/radiusdesk-installer#31]
When I try to add a profile component I get an error message "Select an item" and cannot go ahead any further.

![screen shot 2016-09-15 at 6 46 25 pm](https://cloud.githubusercontent.com/assets/20902391/18561213/96c2dbfc-7b9c-11e6-9952-9a7ab6443e38.png)

**Comment by muffycompo** [comment]
@stan-thomas could you help provide the steps to reproduce this error?
