### ISSUE TITLE
TASK [radiusdesk : Installing Nginx (RHEL/CentOS 6+)]  Failed

### ISSUE THREAD

**Issue by ralphlobo** [muffycompo/radiusdesk-installer#32]
==== RADIUSDesk Installer 1.2.0 ====

1) [I]nstall/Reconfigure RADIUSDesk
2) [Q]uit
Select an Option: 1
Installing/Reconfiguring RADIUSDesk

statically included: /root/radiusdesk/roles/radiusdesk/tasks/Nginx_Debian.yml
statically included: /root/radiusdesk/roles/radiusdesk/tasks/Nginx_RedHat.yml
statically included: /root/radiusdesk/roles/radiusdesk/tasks/Freeradius_Debian.yml
statically included: /root/radiusdesk/roles/radiusdesk/tasks/Freeradius_RedHat.yml
statically included: /root/radiusdesk/roles/radiusdesk/tasks/Nodejs_Debian.yml
statically included: /root/radiusdesk/roles/radiusdesk/tasks/Nodejs_RedHat.yml
statically included: /root/radiusdesk/roles/radiusdesk/tasks/Pptpd_Debian.yml
statically included: /root/radiusdesk/roles/radiusdesk/tasks/Pptpd_RedHat.yml
statically included: /root/radiusdesk/roles/radiusdesk/tasks/Coovachilli_Debian.yml
statically included: /root/radiusdesk/roles/radiusdesk/tasks/Coovachilli_RedHat.yml

PLAY [default] *****************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [radiusdesk : Checking for Supported OS] **********************************
skipping: [localhost]

TASK [radiusdesk : Adding RadiusDesk Variables (Ubuntu 14+)] *******************
skipping: [localhost]

TASK [radiusdesk : Adding RadiusDesk Variables (RHEL/CentOS 6+)] ***************
ok: [localhost]

TASK [radiusdesk : Ensuring Apache is not installed (Ubuntu 14+)] **************
skipping: [localhost]

TASK [radiusdesk : Installing Nginx (Ubuntu 14+)] ******************************
skipping: [localhost]

TASK [radiusdesk : Installing PHP5 packages (Ubuntu 14+)] **********************
skipping: [localhost] => (item=[]) 

TASK [radiusdesk : Installing PHP7 packages (Ubuntu 14+)] **********************
skipping: [localhost] => (item=None) 

TASK [radiusdesk : Installing RadiusDesk packages (Ubuntu 14+)] ****************
skipping: [localhost] => (item=[]) 

TASK [radiusdesk : Configuring PHP5-FPM to use UNIX sockets (Ubuntu 14+)] ******
skipping: [localhost]

TASK [radiusdesk : Configuring PHP7-FPM to use UNIX sockets (Ubuntu 14+)] ******
skipping: [localhost]

TASK [radiusdesk : Configuring Nginx to use UNIX sockets (Ubuntu 14+)] *********
skipping: [localhost]

TASK [radiusdesk : Configuring Nginx for RadiusDesk Web Compression (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Restarting RadiusDesk services for PHP5 (Ubuntu 14+)] *******
skipping: [localhost] => (item=nginx) 
skipping: [localhost] => (item=php-fpm) 

TASK [radiusdesk : Restarting RadiusDesk services for PHP7 (Ubuntu 14+)] *******
skipping: [localhost] => (item=nginx) 
skipping: [localhost] => (item=None) 

TASK [radiusdesk : Downloading CakePHP Source from Github (Ubuntu 14+)] ********
skipping: [localhost]

TASK [radiusdesk : Copying CakePHP Source to Webroot (Ubuntu 14+)] *************
skipping: [localhost]

TASK [radiusdesk : Downloading RadiusDesk CakePHP Source from Subversion (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Copying RadiusDesk CakePHP App Source to Webroot (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Downloading RadiusDesk Viewer Source from Subversion (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Copying RadiusDesk Viewer Source to Webroot (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Downloading RadiusDesk Login Source from Subversion (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Copying RadiusDesk Login Source webroot (Ubuntu 14+)] *******
skipping: [localhost]

TASK [radiusdesk : Configuring UAM Service for RadiusDesk Login (Ubuntu 14+)] **
skipping: [localhost]

TASK [radiusdesk : Checking if we already downloaded ExtJS 6 sources (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Downloading ExtJS 6 sources from Subversion (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Extracting ExtJS 6 archive for RadiusDesk Viewer (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Correcting Webroot ownership and permissions (Ubuntu 14+)] **
skipping: [localhost]

TASK [radiusdesk : Fix PHP5 Default Timezone] **********************************
skipping: [localhost]

TASK [radiusdesk : Fix PHP7 Default Timezone] **********************************
skipping: [localhost]

TASK [radiusdesk : Ensuring Nginx is Started (Ubuntu 14+)] *********************
skipping: [localhost]

TASK [radiusdesk : Ensuring PHP5-FPM is Started (Ubuntu 14+)] ******************
skipping: [localhost]

TASK [radiusdesk : Ensuring PHP7-FPM is Started (Ubuntu 14+)] ******************
skipping: [localhost]

TASK [radiusdesk : Configuring RadiusDesk Cron Jobs (Ubuntu 14+)] **************
skipping: [localhost]

TASK [radiusdesk : Ensuring MySQL is Started (Ubuntu 14+)] *********************
skipping: [localhost]

TASK [radiusdesk : Ensuring MySQL Root password has been set (Ubuntu 14+)] *****
skipping: [localhost]

TASK [radiusdesk : Changing MySQL Root password (Ubuntu 14+)] ******************
skipping: [localhost] => (item=127.0.0.1) 
skipping: [localhost] => (item=localhost) 

TASK [radiusdesk : Adding .my.cnf for MySQL root Password Idempotency (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Remove Anonymous MySQL Users (Ubuntu 14+)] ******************
skipping: [localhost] => (item=127.0.0.1) 
skipping: [localhost] => (item=localhost) 

TASK [radiusdesk : Creating RadiusDesk Database (Ubuntu 14+)] ******************
skipping: [localhost]

TASK [radiusdesk : Creating RadiusDesk Database User (Ubuntu 14+)] *************
skipping: [localhost] => (item=127.0.0.1) 
skipping: [localhost] => (item=localhost) 

TASK [radiusdesk : Importing RadiusDesk Database (Ubuntu 14+)] *****************
skipping: [localhost]

TASK [radiusdesk : Ensuring SELinux is in Permissive Mode (RHEL/CentOS 6+)] ****
ok: [localhost]

TASK [radiusdesk : Ensuring Apache is not installed (RHEL/CentOS 6+)] **********
ok: [localhost]

TASK [radiusdesk : Checking for EPEL Repository (RHEL/CentOS 6+)] **************
ok: [localhost]

TASK [radiusdesk : Installing EPEL Repo for RadiusDesk (RHEL/CentOS 6+)] *******
ok: [localhost]

TASK [radiusdesk : Installing MySQL 5 Repo for RadiusDesk (RHEL/CentOS 6+)] ****
skipping: [localhost]

TASK [radiusdesk : Installing Nginx (RHEL/CentOS 6+)] **************************
fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "msg": "Error: Package: nginx18-1.8.1-1.w6.x86_64 (webtatic)\n           Requires: GeoIP\nError: Package: nginx18-1.8.1-1.w6.x86_64 (webtatic)\n           Requires: libprofiler.so.0()(64bit)\nError: Package: nginx18-1.8.1-1.w6.x86_64 (webtatic)\n           Requires: libGeoIP.so.1()(64bit)\n", "rc": 1, "results": ["Loaded plugins: fastestmirror, refresh-packagekit, replace, security\nSetting up Install Process\nLoading mirror speeds from cached hostfile\n * base: mirror.nbrc.ac.in\n * extras: mirror.nbrc.ac.in\n * updates: mirror.nbrc.ac.in\n * webtatic: sp.repo.webtatic.com\nResolving Dependencies\n--> Running transaction check\n---> Package nginx18.x86_64 0:1.8.1-1.w6 will be installed\n--> Processing Dependency: gd for package: nginx18-1.8.1-1.w6.x86_64\n--> Processing Dependency: GeoIP for package: nginx18-1.8.1-1.w6.x86_64\n--> Processing Dependency: libprofiler.so.0()(64bit) for package: nginx18-1.8.1-1.w6.x86_64\n--> Processing Dependency: libgd.so.2()(64bit) for package: nginx18-1.8.1-1.w6.x86_64\n--> Processing Dependency: libGeoIP.so.1()(64bit) for package: nginx18-1.8.1-1.w6.x86_64\n--> Running transaction check\n---> Package gd.x86_64 0:2.0.35-11.el6 will be installed\n---> Package nginx18.x86_64 0:1.8.1-1.w6 will be installed\n--> Processing Dependency: GeoIP for package: nginx18-1.8.1-1.w6.x86_64\n--> Processing Dependency: libprofiler.so.0()(64bit) for package: nginx18-1.8.1-1.w6.x86_64\n--> Processing Dependency: libGeoIP.so.1()(64bit) for package: nginx18-1.8.1-1.w6.x86_64\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:\ndevtoolset-2-gcc-4.8.2-15.1.el6.x86_64 is a duplicate with devtoolset-2-gcc-4.8.2-15.el6.x86_64\n"]}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/root/radiusdesk/rd-installer-ansible.retry

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1

**Comment by muffycompo** [comment]
Are you using a fresh server install? What OS type are you using?

**Comment by ralphlobo** [comment]
Yes this is a fresh install and im using CentOS 6

**Comment by muffycompo** [comment]
Can you confirm if you are using Python 2.7.9+? Also it keeps failing from package dependency resolution which shows a duplicate package. If you can send a remote access, I can help you take a look as well

**Comment by ralphlobo** [comment]
Hi Im using Python 2.7.6

**Comment by muffycompo** [comment]
Okay, upgrade your version of Python to 2.7.9+ and run the installer again. You can use centos-scl project to help.

**Comment by ralphlobo** [comment]
TASK [radiusdesk : Installing Nginx (RHEL/CentOS 6+)] **************************
fatal: [localhost]: FAILED! => {"changed": true, "failed": true, "msg": "Error: Package: nginx18-1.8.1-1.w6.x86_64 (webtatic)\n           Requires: GeoIP\nError: Package: nginx18-1.8.1-1.w6.x86_64 (webtatic)\n           Requires: libprofiler.so.0()(64bit)\nError: Package: nginx18-1.8.1-1.w6.x86_64 (webtatic)\n           Requires: libGeoIP.so.1()(64bit)\n", "rc": 1, "results": ["Loaded plugins: fastestmirror, refresh-packagekit, replace, security\nSetting up Install Process\nLoading mirror speeds from cached hostfile\n * base: mirror.nbrc.ac.in\n * extras: mirror.nbrc.ac.in\n * updates: mirror.nbrc.ac.in\n * webtatic: sp.repo.webtatic.com\nResolving Dependencies\n--> Running transaction check\n---> Package nginx18.x86_64 0:1.8.1-1.w6 will be installed\n--> Processing Dependency: gd for package: nginx18-1.8.1-1.w6.x86_64\n--> Processing Dependency: GeoIP for package: nginx18-1.8.1-1.w6.x86_64\n--> Processing Dependency: libprofiler.so.0()(64bit) for package: nginx18-1.8.1-1.w6.x86_64\n--> Processing Dependency: libgd.so.2()(64bit) for package: nginx18-1.8.1-1.w6.x86_64\n--> Processing Dependency: libGeoIP.so.1()(64bit) for package: nginx18-1.8.1-1.w6.x86_64\n--> Running transaction check\n---> Package gd.x86_64 0:2.0.35-11.el6 will be installed\n---> Package nginx18.x86_64 0:1.8.1-1.w6 will be installed\n--> Processing Dependency: GeoIP for package: nginx18-1.8.1-1.w6.x86_64\n--> Processing Dependency: libprofiler.so.0()(64bit) for package: nginx18-1.8.1-1.w6.x86_64\n--> Processing Dependency: libGeoIP.so.1()(64bit) for package: nginx18-1.8.1-1.w6.x86_64\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n** Found 1 pre-existing rpmdb problem(s), 'yum check' output follows:\ndevtoolset-2-gcc-4.8.2-15.1.el6.x86_64 is a duplicate with devtoolset-2-gcc-4.8.2-15.el6.x86_64\n"]}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/root/radiusdesk/rd-installer-ansible.retry

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=0    unreachable=0    failed=1   

[root@127 radiusdesk]# python -v
bash: usr/local/bin/python3.5: No such file or directory

[root@127 radiusdesk]# python3 --version
Python 3.5.0

**Comment by ralphlobo** [comment]
Tried Again and yes i did face the same issue

**Comment by muffycompo** [comment]
Can you give me remote access? I will like to take a look. Probably start with a fresh install of CentOS 6...
