### ISSUE TITLE
FATAL LOCALHOST FAILED

### ISSUE THREAD

**Issue by vicantec** [muffycompo/radiusdesk-installer#33]
Sorry, have failed during installation, can you help?

fatal: [localhost]: FAILED! => {"failed": true, "msg": "The conditional check 'enable_pptpd_support and ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '14'' failed. The error was: error while evaluating conditional (enable_pptpd_support and ansible_distribution == 'Ubuntu' and ansible_distribution_version >= '14'): 'enable_pptpd_support' is undefined\n\nThe error appears to have been in '/home/victor/radiusdesk-installer/roles/radiusdesk/tasks/main.yml': line 39, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: RadiusDesk PPTPD Setup (Ubuntu 14+)\n  ^ here\n"}

**Comment by muffycompo** [comment]
What OS are you running the Installer on? Also confirm that your version of Python is 2.7.9+

**Comment by vicantec** [comment]
It was linux mint, i reinstall in ubuntu 14.04 and works fine, thank you.

**Comment by muffycompo** [comment]
Okay great. Also, if you have some time, we could work on a Linux Mint port :)

**Comment by vicantec** [comment]
Overload at this moment, but i will think on it. 
Ubuntu 16.04 it´s a good goal too.
You give us a very nice job!! thank you  for your efforts.

**Comment by muffycompo** [comment]
Okay, Ubuntu 16+ support will be added later today or tomorrow, haven't gotten around to push many of the changes to github. Thanks for the feedback as well.
