### ISSUE TITLE
Installing Failed

### ISSUE THREAD

**Issue by nicktereh** [muffycompo/radiusdesk-installer#35]
Hello,
I have a problem :(

./rd-installer

==== RADIUSDesk Installer 1.2.0 ====

1) [I]nstall/Reconfigure RADIUSDesk
2) [Q]uit
Select an Option: i
Installing/Reconfiguring RADIUSDesk

PLAY [default] *****************************************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [radiusdesk : Checking for Supported OS] **********************************
skipping: [localhost]

TASK [radiusdesk : Adding RadiusDesk Variables (Ubuntu 14+)] *******************
skipping: [localhost]

TASK [radiusdesk : Adding RadiusDesk Variables (RHEL/CentOS 6+)] ***************
ok: [localhost]

TASK [radiusdesk : Ensuring Apache is not installed (Ubuntu 14+)] **************
skipping: [localhost]

TASK [radiusdesk : Installing Nginx (Ubuntu 14+)] ******************************
skipping: [localhost]

TASK [radiusdesk : Installing PHP5 packages (Ubuntu 14+)] **********************
skipping: [localhost] => (item=[])

TASK [radiusdesk : Installing PHP7 packages (Ubuntu 14+)] **********************
skipping: [localhost] => (item=None)

TASK [radiusdesk : Installing RadiusDesk packages (Ubuntu 14+)] ****************
skipping: [localhost] => (item=[])

TASK [radiusdesk : Installing RadiusDesk packages (Ubuntu 16+)] ****************
skipping: [localhost] => (item=[])

TASK [radiusdesk : Configuring PHP5-FPM to use UNIX sockets (Ubuntu 14+)] ******
skipping: [localhost]

TASK [radiusdesk : Configuring PHP7-FPM to use UNIX sockets (Ubuntu 14+)] ******
skipping: [localhost]

TASK [radiusdesk : Configuring Nginx to use UNIX sockets (Ubuntu 14+)] *********
skipping: [localhost]

TASK [radiusdesk : Configuring Nginx for RadiusDesk Web Compression (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Restarting RadiusDesk services for PHP5 (Ubuntu 14+)] *******
skipping: [localhost] => (item=php-fpm)
skipping: [localhost] => (item=nginx)

TASK [radiusdesk : Restarting RadiusDesk services for PHP7 (Ubuntu 14+)] *******
skipping: [localhost] => (item=nginx)
skipping: [localhost] => (item=None)

TASK [radiusdesk : Downloading CakePHP Source from Github (Ubuntu 14+)] ********
skipping: [localhost]

TASK [radiusdesk : Copying CakePHP Source to Webroot (Ubuntu 14+)] *************
skipping: [localhost]

TASK [radiusdesk : Downloading RadiusDesk CakePHP Source from Subversion (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Copying RadiusDesk CakePHP App Source to Webroot (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Downloading RadiusDesk Viewer Source from Subversion (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Copying RadiusDesk Viewer Source to Webroot (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Downloading RadiusDesk Login Source from Subversion (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Copying RadiusDesk Login Source webroot (Ubuntu 14+)] *******
skipping: [localhost]

TASK [radiusdesk : Configuring UAM Service for RadiusDesk Login (Ubuntu 14+)] **
skipping: [localhost]

TASK [radiusdesk : Checking if we already downloaded ExtJS 6 sources (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Downloading ExtJS 6 sources from Subversion (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Extracting ExtJS 6 archive for RadiusDesk Viewer (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Correcting Webroot ownership and permissions (Ubuntu 14+)] **
skipping: [localhost]

TASK [radiusdesk : Fix PHP5 Default Timezone] **********************************
skipping: [localhost]

TASK [radiusdesk : Fix PHP7 Default Timezone] **********************************
skipping: [localhost]

TASK [radiusdesk : Ensuring Nginx is Started (Ubuntu 14+)] *********************
skipping: [localhost]

TASK [radiusdesk : Ensuring PHP5-FPM is Started (Ubuntu 14+)] ******************
skipping: [localhost]

TASK [radiusdesk : Ensuring PHP7-FPM is Started (Ubuntu 14+)] ******************
skipping: [localhost]

TASK [radiusdesk : Configuring RadiusDesk Cron Jobs (Ubuntu 14+)] **************
skipping: [localhost]

TASK [radiusdesk : Ensuring MySQL is Started (Ubuntu 14+)] *********************
skipping: [localhost]

TASK [radiusdesk : Ensuring MySQL Root password has been set (Ubuntu 14+)] *****
skipping: [localhost]

TASK [radiusdesk : Changing MySQL Root password (Ubuntu 14+)] ******************
skipping: [localhost] => (item=127.0.0.1)
skipping: [localhost] => (item=localhost)

TASK [radiusdesk : Adding .my.cnf for MySQL root Password Idempotency (Ubuntu 14+)] ***
skipping: [localhost]

TASK [radiusdesk : Remove Anonymous MySQL Users (Ubuntu 14+)] ******************
skipping: [localhost] => (item=localhost)
skipping: [localhost] => (item=127.0.0.1)

TASK [radiusdesk : Creating RadiusDesk Database (Ubuntu 14+)] ******************
skipping: [localhost]

TASK [radiusdesk : Creating RadiusDesk Database User (Ubuntu 14+)] *************
skipping: [localhost] => (item=localhost)
skipping: [localhost] => (item=127.0.0.1)

TASK [radiusdesk : Importing RadiusDesk Database (Ubuntu 14+)] *****************
skipping: [localhost]

TASK [radiusdesk : Ensuring SELinux is in Permissive Mode (RHEL/CentOS 6+)] ****
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Destination /etc/sysconfig/selinux does not exist !", "rc": 257}
        to retry, use: --limit @/root/radiusdesk-installer/rd-installer-ansible.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1

**Comment by nicktereh** [comment]
CentOS 7.2+
VPS (mycloud.by Jelastic)
SMP Tue Dec 13 20:58:28 MSK 2016 x86_64 x86_64 x86_64 GNU/Linux

**Comment by nicktereh** [comment]
sestatus
SELinux status:                 disabled

**Comment by muffycompo** [comment]
@nicktereh there has been a couple of commits to the installer addressing a whole number of things. I have tried the installer on a fresh installation of CentOS 7.3+ and it ran successfully. Kindly try the new script and let us know if it worked for you.

**Comment by nicktereh** [comment]
I found the solution)

My server did not have a file /etc/selinux/config
I just created the file and wrote this code

`# This file controls the state of SELinux on the system.
# SELINUX= can take one of these three values:
#       enforcing - SELinux security policy is enforced.
#       permissive - SELinux prints warnings instead of enforcing.
#       disabled - SELinux is fully disabled.
SELINUX=permissive
# SELINUXTYPE= type of policy in use. Possible values are:
#       targeted - Only targeted network daemons are protected.
#       strict - Full SELinux protection.
SELINUXTYPE=targeted

# SETLOCALDEFS= Check local definition changes
SETLOCALDEFS=0`
