### ISSUE TITLE
Installation Problem

### ISSUE THREAD

**Issue by cleqo** [muffycompo/radiusdesk-installer#36]
Im getting this fail In Ubuntu 16.04:

failed: [localhost] (item=127.0.0.1) => {"failed": true, "item": "127.0.0.1", "msg": "unable to connect to database, check login_user and login_password are correct or /home/ubuntu/.my.cnf has the credentials. Exception message: (1045, \"Acces
s denied for user '********'@'localhost' (using password: NO)\")"}

Radiusdesk runs, but neither the console shows any freeradius logs in the app, neither the radius functions seems to work.

**Comment by muffycompo** [comment]
@cleqo was it a fresh installation of Ubuntu 16.04? I just tried it on a fresh install on Digital Ocean and it ran successfully. The logs shows as well...

**Comment by cleqo** [comment]
Was a fresh installation in AWS, but i can´t make it work ill try in digital ocean as well.

**Comment by muffycompo** [comment]
Okay let us know how it goes @cleqo

**Comment by cleqo** [comment]
got: 
TASK [radiusdesk : Configuring CoovaChilli for RadiusDesk (Ubuntu 14+)] ********                                                                                                                                                                   
fatal: [localhost]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'coovachilii_group' is undefined\n\nThe error appears to have been in '/home/u
buntu/radiusdesk-installer/roles/radiusdesk/tasks/Coovachilli_Debian.yml': line 36, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Configuring CoovaChilli fo
r RadiusDesk (Ubuntu 14+)\n  ^ here\n"}     

The same state as before most apps well configured but the whole system does not seems to work:
![mosaic capture 2017-03-30 at 20 24 29](https://cloud.githubusercontent.com/assets/469839/24533752/f093173a-1586-11e7-9ed8-05a393b96f7f.png)

Is there any chance you could build an AMI for Amazon so the community could use it?

I´m considering importing the ova in sourceforge to AWS, but i rather preffer to been using this installer to better and more granular control of the process.

**Comment by muffycompo** [comment]
Okay, I will push a patch to the error and build an AMI as requested. Will let you test it before making it public. Thanks for testing it out and reporting the bugs...Will let you know as soon as I fix the issue.

**Comment by cleqo** [comment]
You were right, digitialocean droplet works just fine, but i was not able to do it in AWS AMI´s
