### ISSUE TITLE
Error - Adding RadiusDesk MAO Apt Repository Key (Ubuntu 14+)

### ISSUE THREAD

**Issue by fotorider** [muffycompo/radiusdesk-installer#38]
Please help with issue. How to fix it? Thanks in advance.

TASK [radiusdesk : Adding RadiusDesk MAO Apt Repository Key (Ubuntu 14+)] ****************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "cmd": "/usr/bin/apt-key add -", "failed": true, "msg": "gpg: no valid OpenPGP data found.", "rc": 2, "stderr": "gpg: no valid OpenPGP data found.\n", "stderr_lines": ["gpg: no valid OpenPGP data found."], "stdout": "", "stdout_lines": []}

**Comment by muffycompo** [comment]
The domain resolution has been fixed now. Also ensure you are not using Google public DNS servers (8.8.8.8 and 8.8.4.4).

**Comment by MarujoNagoF** [comment]
hi I am getting this error:
HTTP Error 404 (http://aropoly....)
