### ISSUE TITLE
Failed to Install Freeradius during installation

### ISSUE THREAD

**Issue by josephopio11** [muffycompo/radiusdesk-installer#39]
==== RADIUSDesk Installer 1.2.1 ====

1) [I]nstall RADIUSDesk
2) Install RADIUSDesk + [C]oovaChilli
Select an Option or [q] to Quit: 2
Installing RADIUSDesk + CoovaChilli

CoovaChilli LAN Interface (default: eth0): 
CoovaChilli WAN Interface (default: eth1): 
CoovaChilli UAM Secret (default: greatsecret): 
eth0 - eth1 - greatsecret

PLAY [default] ************************************************************************************************

TASK [Gathering Facts] ****************************************************************************************
ok: [localhost]

TASK [radiusdesk : Checking for Supported Ubuntu Release] *****************************************************
skipping: [localhost]

TASK [radiusdesk : Checking for Supported RHEL/CentOS Release] ************************************************
skipping: [localhost]

TASK [radiusdesk : Adding RadiusDesk Variables (Ubuntu 14+)] **************************************************
skipping: [localhost]

TASK [radiusdesk : Adding RadiusDesk Variables (RHEL/CentOS 6+)] **********************************************
ok: [localhost]

TASK [radiusdesk : Ensuring AppArmor is disabled (Ubuntu 14+)] ************************************************
skipping: [localhost]

TASK [radiusdesk : Bootstraping Download Directory for RADIUSDesk Sources (Ubuntu 14+)] ***********************
skipping: [localhost]

TASK [radiusdesk : Ensuring Apache is not installed (Ubuntu 14+)] *********************************************
skipping: [localhost]

TASK [radiusdesk : Installing Nginx (Ubuntu 14+)] *************************************************************
skipping: [localhost]

TASK [radiusdesk : Installing PHP5 packages (Ubuntu 14+)] *****************************************************
skipping: [localhost] => (item=[]) 

TASK [radiusdesk : Installing PHP7 packages (Ubuntu 14+)] *****************************************************
skipping: [localhost] => (item=None) 

TASK [radiusdesk : Installing RadiusDesk packages (Ubuntu 14+)] ***********************************************
skipping: [localhost] => (item=[]) 

TASK [radiusdesk : Installing RadiusDesk packages (Ubuntu 16+)] ***********************************************
skipping: [localhost] => (item=[]) 

TASK [radiusdesk : Configuring PHP5-FPM to use UNIX sockets (Ubuntu 14+)] *************************************
skipping: [localhost]

TASK [radiusdesk : Configuring PHP7-FPM to use UNIX sockets (Ubuntu 14+)] *************************************
skipping: [localhost]

TASK [radiusdesk : Configuring Nginx to use UNIX sockets (Ubuntu 14+)] ****************************************
skipping: [localhost]

TASK [radiusdesk : Configuring Nginx for RadiusDesk Web Compression (Ubuntu 14+)] *****************************
skipping: [localhost]

TASK [radiusdesk : Restarting RadiusDesk services for PHP5 (Ubuntu 14+)] **************************************
skipping: [localhost] => (item=nginx) 
skipping: [localhost] => (item=php-fpm) 

TASK [radiusdesk : Restarting RadiusDesk services for PHP7 (Ubuntu 14+)] **************************************
skipping: [localhost] => (item=nginx) 
skipping: [localhost] => (item=None) 

TASK [radiusdesk : Downloading CakePHP Source from Github (Ubuntu 14+)] ***************************************
skipping: [localhost]

TASK [radiusdesk : Copying CakePHP Source to Webroot (Ubuntu 14+)] ********************************************
skipping: [localhost]

TASK [radiusdesk : Downloading RadiusDesk CakePHP Source from Subversion (Ubuntu 14+)] ************************
skipping: [localhost]

TASK [radiusdesk : Copying RadiusDesk CakePHP App Source to Webroot (Ubuntu 14+)] *****************************
skipping: [localhost]

TASK [radiusdesk : Downloading RadiusDesk CakePHP 3 Source from Subversion (Ubuntu 14+)] **********************
skipping: [localhost]

TASK [radiusdesk : Copying RadiusDesk CakePHP 3 Source to Webroot (Ubuntu 14+)] *******************************
skipping: [localhost]

TASK [radiusdesk : Downloading RadiusDesk Viewer Source from Subversion (Ubuntu 14+)] *************************
skipping: [localhost]

TASK [radiusdesk : Copying RadiusDesk Viewer Source to Webroot (Ubuntu 14+)] **********************************
skipping: [localhost]

TASK [radiusdesk : Downloading RadiusDesk Login Source from Subversion (Ubuntu 14+)] **************************
skipping: [localhost]

TASK [radiusdesk : Copying RadiusDesk Login Source webroot (Ubuntu 14+)] **************************************
skipping: [localhost]

TASK [radiusdesk : Configuring UAM Service for RadiusDesk Login (Ubuntu 14+)] *********************************
skipping: [localhost]

TASK [radiusdesk : Checking if we already downloaded ExtJS 6.2 sources (Ubuntu 14+)] **************************
skipping: [localhost]

TASK [radiusdesk : Downloading ExtJS 6.2 sources from Subversion (Ubuntu 14+)] ********************************
skipping: [localhost]

TASK [radiusdesk : Extracting ExtJS 6.2 archive for RadiusDesk Viewer (Ubuntu 14+)] ***************************
skipping: [localhost]

TASK [radiusdesk : Correcting Webroot ownership and permissions (Ubuntu 14+)] *********************************
skipping: [localhost]

TASK [radiusdesk : Fix PHP5 Default Timezone] *****************************************************************
skipping: [localhost]

TASK [radiusdesk : Fix PHP7 Default Timezone] *****************************************************************
skipping: [localhost]

TASK [radiusdesk : Ensuring Nginx is Started (Ubuntu 14+)] ****************************************************
skipping: [localhost]

TASK [radiusdesk : Ensuring PHP5-FPM is Started (Ubuntu 14+)] *************************************************
skipping: [localhost]

TASK [radiusdesk : Ensuring PHP7-FPM is Started (Ubuntu 14+)] *************************************************
skipping: [localhost]

TASK [radiusdesk : Configuring RadiusDesk Cron Jobs (Ubuntu 14+)] *********************************************
skipping: [localhost]

TASK [radiusdesk : Disabling MySQL 5.7 Strict Mode (Ubuntu 16+)] **********************************************
skipping: [localhost]

TASK [radiusdesk : Ensuring MySQL is Started (Ubuntu 14+)] ****************************************************
skipping: [localhost]

TASK [radiusdesk : Ensuring MySQL Root password has been set (Ubuntu 14+)] ************************************
skipping: [localhost]

TASK [radiusdesk : Changing MySQL Root password (Ubuntu 14+)] *************************************************
skipping: [localhost] => (item=127.0.0.1) 
skipping: [localhost] => (item=localhost) 

TASK [radiusdesk : Adding .my.cnf for MySQL root Password Idempotency (Ubuntu 14+)] ***************************
skipping: [localhost]

TASK [radiusdesk : Remove Anonymous MySQL Users (Ubuntu 14+)] *************************************************
skipping: [localhost] => (item=127.0.0.1) 
skipping: [localhost] => (item=localhost) 

TASK [radiusdesk : Creating RadiusDesk Database (Ubuntu 14+)] *************************************************
skipping: [localhost]

TASK [radiusdesk : Creating RadiusDesk Database User (Ubuntu 14+)] ********************************************
skipping: [localhost] => (item=127.0.0.1) 
skipping: [localhost] => (item=localhost) 

TASK [radiusdesk : Importing RadiusDesk Database (Ubuntu 14+)] ************************************************
skipping: [localhost]

TASK [radiusdesk : Installing System Packages (RHEL/CentOS 6+)] ***********************************************
ok: [localhost]

TASK [radiusdesk : Disabling SELinux (RHEL/CentOS 6+)] ********************************************************
ok: [localhost]

TASK [radiusdesk : Bootstraping Download Directory for RADIUSDesk Sources (Ubuntu 14+)] ***********************
ok: [localhost]

TASK [radiusdesk : Ensuring Apache is not installed (RHEL/CentOS 6+)] *****************************************
changed: [localhost]

TASK [radiusdesk : Installing EPEL Repo for RadiusDesk (RHEL/CentOS 6+)] **************************************
ok: [localhost]

TASK [radiusdesk : Installing REMI Repo for RadiusDesk (RHEL/CentOS 6+)] **************************************
ok: [localhost]

TASK [radiusdesk : Installing MySQL Community Repo for RadiusDesk (RHEL/CentOS 6+)] ***************************
ok: [localhost]

TASK [radiusdesk : Installing Nginx (RHEL/CentOS 6+)] *********************************************************
ok: [localhost]

TASK [radiusdesk : Installing PHP packages (RHEL/CentOS 6+)] **************************************************
ok: [localhost] => (item=[u'php-fpm', u'php-pear', u'php-gd', u'php-common', u'php-cli', u'php-mysql', u'php-xcache', u'php-intl', u'php-xml', u'php-mbstring'])

TASK [radiusdesk : Installing RadiusDesk packages (RHEL/CentOS 6+)] *******************************************
ok: [localhost] => (item=[u'mysql-server', u'mysql', u'subversion', u'git', u'cronie', u'mailx', u'python', u'MySQL-python', u'perl', u'unixODBC', u'postgresql', u'openldap', u'libtool-ltdl', u'gcc-c++', u'gcc', u'make', u'unzip', u'tar'])

TASK [radiusdesk : Configuring PHP-FPM to use UNIX sockets (RHEL/CentOS 6+)] **********************************
ok: [localhost]

TASK [radiusdesk : Configuring Nginx to use UNIX sockets (RHEL/CentOS 6+)] ************************************
ok: [localhost]

TASK [radiusdesk : Configuring Nginx for RadiusDesk Web Compression (RHEL/CentOS 6+)] *************************
ok: [localhost]

TASK [radiusdesk : Downloading CakePHP Source from Github (RHEL/CentOS 6+)] ***********************************
ok: [localhost]

TASK [radiusdesk : Copying CakePHP Source to Webroot (RHEL/CentOS 6+)] ****************************************
changed: [localhost]

TASK [radiusdesk : Downloading RadiusDesk CakePHP Source from Subversion (RHEL/CentOS 6+)] ********************
 [WARNING]: Consider using subversion module rather than running svn

changed: [localhost]

TASK [radiusdesk : Copying RadiusDesk CakePHP App Source to Webroot (RHEL/CentOS 6+)] *************************
changed: [localhost]

TASK [radiusdesk : Downloading RadiusDesk CakePHP 3 Source from Subversion (Ubuntu 14+)] **********************
changed: [localhost]

TASK [radiusdesk : Copying RadiusDesk CakePHP 3 Source to Webroot (Ubuntu 14+)] *******************************
changed: [localhost]

TASK [radiusdesk : Downloading RadiusDesk Viewer Source from Subversion (RHEL/CentOS 6+)] *********************
changed: [localhost]

TASK [radiusdesk : Copying RadiusDesk Viewer Source to Webroot (RHEL/CentOS 6+)] ******************************
changed: [localhost]

TASK [radiusdesk : Downloading RadiusDesk Login Source from Subversion (RHEL/CentOS 6+)] **********************
changed: [localhost]

TASK [radiusdesk : Copying RadiusDesk Login Source webroot (RHEL/CentOS 6+)] **********************************
changed: [localhost]

TASK [radiusdesk : Configuring UAM Service for RadiusDesk Login (RHEL/CentOS 6+)] *****************************
changed: [localhost]

TASK [radiusdesk : Checking if we already downloaded ExtJS 6.2 sources (Ubuntu 14+)] **************************
ok: [localhost]

TASK [radiusdesk : Downloading ExtJS 6.2 sources from Subversion (Ubuntu 14+)] ********************************
 [WARNING]: when statements should not include jinja2 templating delimiters such as {{ }} or {% %}. Found:
extjs_src.stat.exists == False or extjs_src.stat.md5 != '{{ extjs_62_src_md5_sum }}'

skipping: [localhost]

TASK [radiusdesk : Extracting ExtJS 6.2 archive for RadiusDesk Viewer (Ubuntu 14+)] ***************************
changed: [localhost]

TASK [radiusdesk : Correcting Webroot ownership and permissions (RHEL/CentOS 6+)] *****************************
changed: [localhost]

TASK [radiusdesk : Fix PHP Default Timezone] ******************************************************************
changed: [localhost]

TASK [radiusdesk : Ensuring Nginx is Started (RHEL/CentOS 6+)] ************************************************
changed: [localhost]

TASK [radiusdesk : Ensuring PHP-FPM is Started (RHEL/CentOS 6+)] **********************************************
changed: [localhost]

TASK [radiusdesk : Configuring RadiusDesk Cron Jobs (RHEL/CentOS 6+)] *****************************************
ok: [localhost]

TASK [radiusdesk : Disabling MySQL 5.6+ Strict Mode (RHEL/CentOS 6+)] *****************************************
ok: [localhost]

TASK [radiusdesk : Ensuring MySQL is Started (RHEL/CentOS 6+)] ************************************************
ok: [localhost]

TASK [radiusdesk : Ensuring MySQL Root password has been set (RHEL/CentOS 6+)] ********************************
ok: [localhost]

TASK [radiusdesk : Changing MySQL Root password (RHEL/CentOS 6+)] *********************************************
skipping: [localhost] => (item=127.0.0.1) 
skipping: [localhost] => (item=localhost) 

TASK [radiusdesk : Adding .my.cnf for MySQL root Password Idempotency (RHEL/CentOS 6+)] ***********************
skipping: [localhost]

TASK [radiusdesk : Remove Anonymous MySQL Users (RHEL/CentOS 6+)] *********************************************
ok: [localhost] => (item=127.0.0.1)
ok: [localhost] => (item=localhost)

TASK [radiusdesk : Creating RadiusDesk Database (RHEL/CentOS 6+)] *********************************************
ok: [localhost]

TASK [radiusdesk : Creating RadiusDesk Database User (RHEL/CentOS 6+)] ****************************************
ok: [localhost] => (item=127.0.0.1)
ok: [localhost] => (item=localhost)

TASK [radiusdesk : Importing RadiusDesk Database (RHEL/CentOS 6+)] ********************************************
changed: [localhost]

TASK [radiusdesk : Adding RadiusDesk MAO Apt Repository Key (Ubuntu 14+)] *************************************
skipping: [localhost]

TASK [radiusdesk : Adding RadiusDesk MAO Apt Main Repository (Ubuntu 14+)] ************************************
skipping: [localhost]

TASK [radiusdesk : Installing Freeradius for RadiusDesk (Ubuntu 14+)] *****************************************
skipping: [localhost] => (item=[]) 

TASK [radiusdesk : Checking if we already have Freeradius Configuration Directory Backup (Ubuntu 14+)] ********
skipping: [localhost]

TASK [radiusdesk : Renaming Freeradius Configuration Directory (Ubuntu 14+)] **********************************
skipping: [localhost]

TASK [radiusdesk : Removing Old Freeradius Configuration Directory (Ubuntu 14+)] ******************************
skipping: [localhost]

TASK [radiusdesk : Extracting RadiusDesk Freeradius Configuration (Ubuntu 14+)] *******************************
skipping: [localhost]

TASK [radiusdesk : Configuring Freeradius Configuration Directory (Ubuntu 14+)] *******************************
skipping: [localhost]

TASK [radiusdesk : Configuring RadiusDesk Freeradius radiusd.conf (Ubuntu 14+)] *******************************
skipping: [localhost]

TASK [radiusdesk : Configuring RadiusDesk Freeradius Dictionary (Ubuntu 14+)] *********************************
skipping: [localhost]

TASK [radiusdesk : Configuring RadiusDesk Freeradius Checkrad Script (Ubuntu 14+)] ****************************
skipping: [localhost]

TASK [radiusdesk : Configuring RadiusDesk Freeradius Dynamic Clients (Ubuntu 14+)] ****************************
skipping: [localhost]

TASK [radiusdesk : Correcting radclient paths for radscenario.pl Script (Ubuntu 14+)] *************************
skipping: [localhost]

TASK [radiusdesk : Correcting RadiusDesk paths for Freeradius (Ubuntu 14+)] ***********************************
skipping: [localhost]

TASK [radiusdesk : Correcting MESHDesk paths for Freeradius (Ubuntu 14+)] *************************************
skipping: [localhost]

TASK [radiusdesk : Correcting APProfiles paths for Freeradius (Ubuntu 14+)] ***********************************
skipping: [localhost]

TASK [radiusdesk : Configuring radmin_wrapper.pl Script for RadiusDesk (Ubuntu 14+)] **************************
skipping: [localhost]

TASK [radiusdesk : Disabling sudoers Requiretty Option (Ubuntu 14+)] ******************************************
skipping: [localhost]

TASK [radiusdesk : Adding Webroot User to sudoers (Ubuntu 14+)] ***********************************************
skipping: [localhost]

TASK [radiusdesk : Ensuring Freeradius is ready for use (Ubuntu 14+)] *****************************************
skipping: [localhost]

TASK [radiusdesk : Adding RadiusDesk MAO Yum Repository (RHEL/CentOS 6+)] *************************************
changed: [localhost]

TASK [radiusdesk : Installing Freeradius for RadiusDesk (RHEL/CentOS 6+)] *************************************
failed: [localhost] (item=[u'freeradius-3.0.11*', u'freeradius-mysql-3.0.11*', u'freeradius-perl-3.0.11*', u'freeradius-python-3.0.11*', u'freeradius-ldap-3.0.11*', u'freeradius-utils-3.0.11*', u'freeradius-krb5-3.0.11*']) => {"failed": true, "item": ["freeradius-3.0.11*", "freeradius-mysql-3.0.11*", "freeradius-perl-3.0.11*", "freeradius-python-3.0.11*", "freeradius-ldap-3.0.11*", "freeradius-utils-3.0.11*", "freeradius-krb5-3.0.11*"], "msg": "Failure talking to yum: Cannot retrieve repository metadata (repomd.xml) for repository: maomuffy. Please verify its path and try again"}
	to retry, use: --limit @/root/radiusdesk-installer/rd-installer-ansible.retry

PLAY RECAP ****************************************************************************************************
localhost                  : ok=41   changed=18   unreachable=0    failed=1   

[root@localhost radiusdesk-installer]#

Please help. I have tried it over and over. I am using CentOS 6.9. Tried it on CentOS 7 too but failed

**Comment by muffycompo** [comment]
It seemed to be an issue with the maomuffy.com domain not resolving but it has now been fixed.
