### ISSUE TITLE
getting key error

### ISSUE THREAD

**Issue by skoenman** [muffycompo/radiusdesk-installer#40]
hey man hope you can maybe help...im getting this error???
TASK [radiusdesk : Adding RadiusDesk MAO Apt Repository Key (Ubuntu 14+)] *******************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to download key at http://maomuffy.com/apt/ubuntu/apt_keys/rd_installer_mao.asc: Request failed: <urlopen error [Errno -3] Temporary failure in name resolution>"}
        to retry, use: --limit @/root/radiusdesk-installer/rd-installer-ansible.retry

PLAY RECAP **********************************************************************************************************************************************************
localhost                  : ok=37   changed=16   unreachable=0    failed=1

seems like you website may be down???

**Comment by theScrabi** [comment]
I'm having the same error :(
The installer is unusable without that website.

**Comment by muffycompo** [comment]
The URL has been update guys. Sorry for the delay also.
