### ISSUE TITLE
cannot connect to database

### ISSUE THREAD

**Issue by kiyatys** [muffycompo/radiusdesk-installer#41]
Centos 7 Fresh Install

TASK [radiusdesk : Changing MySQL Root password (RHEL/CentOS 6+)] **************
failed: [localhost] (item=127.0.0.1) => {"failed": true, "item": "127.0.0.1", "msg": "unable to connect to database, check login_user and login_password are correct or /********/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user '********'@'localhost' (using password: NO)\")"}
failed: [localhost] (item=localhost) => {"failed": true, "item": "localhost", "msg": "unable to connect to database, check login_user and login_password are correct or /********/.my.cnf has the credentials. Exception message: (1045, \"Access denied for user '********'@'localhost' (using password: NO)\")"}

iptable and selinux disabled, can you give help?

**Comment by muffycompo** [comment]
@kiyatys thanks for reporting this issue. The installer has been updated with many bugs squashed. Give it a try again when you have the time. Regards!
