### ISSUE TITLE
-bash: /usr/bin/node: Too many levels of symbolic links

### ISSUE THREAD

**Issue by golimer** [muffycompo/radiusdesk-installer#42]
TASK [radiusdesk : Reloading Nodejs Socket.io Daemon (Ubuntu 16+)] *********************************************************************************************************************************************************
fatal: [172.21.1.1]: FAILED! => {"changed": true, "cmd": "systemctl daemon-reload && systemctl enable nodejs-socket-io && systemctl start nodejs-socket-io", "delta": "0:00:00.191369", "end": "2018-01-17 10:09:43.856462", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2018-01-17 10:09:43.665093", "stderr": "Created symlink from /etc/systemd/system/multi-user.target.wants/nodejs-socket-io.service to /lib/systemd/system/nodejs-socket-io.service.\nJob for nodejs-socket-io.service failed because the control process exited with error code. See \"systemctl status nodejs-socket-io.service\" and \"journalctl -xe\" for details.", "stderr_lines": ["Created symlink from /etc/systemd/system/multi-user.target.wants/nodejs-socket-io.service to /lib/systemd/system/nodejs-socket-io.service.", "Job for nodejs-socket-io.service failed because the control process exited with error code. See \"systemctl status nodejs-socket-io.service\" and \"journalctl -xe\" for details."], "stdout": "", "stdout_lines": []}

**Comment by muffycompo** [comment]
Thanks @golimer for the feedback. It has been fixed in the latest update. Give it  try when you have the time. Regards!
