### ISSUE TITLE
Ubuntu 16.10 repository is gone

### ISSUE THREAD

**Issue by CptChaos** [muffycompo/radiusdesk-installer#43]
Since the Ubuntu 16.10 repo has been removed, maybe upgrade this awesome script to support Ubuntu 17.04 and/or 17.10?

**Comment by muffycompo** [comment]
Working on it @CptChaos , will keep you posted

**Comment by CptChaos** [comment]
Amazing! If I would master Ansible a lot, I'd be glad to help, but I do barely know how to run playbooks, hahaha!

**Comment by muffycompo** [comment]
@CptChaos I have finally updated the packages to work with only the Supported Ubuntu release since maintaining packages for Unsupported release only gets trickier. The Installer now supports Ubuntu 14.04/16.04/17.10 and ready for the upcoming Ubuntu 18.04 release. Thanks for your feedback.
