### ISSUE TITLE
Error: TASK [radiusdesk : Downloading RadiusDesk CakePHP Source from Subversion (Ubuntu 14+)] 

### ISSUE THREAD

**Issue by alternativetel** [muffycompo/radiusdesk-installer#44]
Hello,

I try to install into a Ubuntu 16.04 Server.

I have this error.....

TASK [radiusdesk : Downloading RadiusDesk CakePHP Source from Subversion (Ubuntu 14+)] *********************************************
 [WARNING]: Consider using subversion module rather than running svn

fatal: [localhost]: FAILED! => {"changed": true, "cmd": "svn checkout -r 2085 https://svn.code.sf.net/p/radiusdesk/code/trunk/rd_cake /tmp/rd_sources/rd_cake", "delta": "0:00:00.314358", "end": "2018-02-16 01:29:31.176404", "msg": "non-zero return code", "rc": 1, "start": "2018-02-16 01:29:30.862046", "stderr": "svn: E170013: Unable to connect to a repository at URL 'https://svn.code.sf.net/p/radiusdesk/code/trunk/rd_cake'\nsvn: E175002: Unexpected HTTP status 502 'Bad Gateway' on '/p/radiusdesk/code/trunk/rd_cake'", "stderr_lines": ["svn: E170013: Unable to connect to a repository at URL 'https://svn.code.sf.net/p/radiusdesk/code/trunk/rd_cake'", "svn: E175002: Unexpected HTTP status 502 'Bad Gateway' on '/p/radiusdesk/code/trunk/rd_cake'"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/root/radiusdesk-installer/rd-installer-ansible.retry

**Comment by muffycompo** [comment]
Thanks @alternativetel for reporting this. The issue has been fixed in the recent update, kindly give it a try and revert if there are more issues.
