### ISSUE TITLE
no statistic for user

### ISSUE THREAD

**Issue by golimer** [muffycompo/radiusdesk-installer#45]
Hello 

I use redhat and external mysql server (aws) after migrating to external mysql, no showing user statistics. Can someone  advice what to edit ?

**Comment by muffycompo** [comment]
@golimer can you confirm that RADIUSDesk is not using references to localhost? This is because the installer does a default installation with localhost as the local MySQL instance.

**Comment by golimer** [comment]
Yes it's true. So that is why asking where to change variable.... :( cause i use aws and have seperate mysql is much safer than in one place with plaintext passwords :)

**Comment by muffycompo** [comment]
To make changes to some of the variables, check roles/radiusdesk/vars/RedHat.yml. Look for variables like rd_db_user, rd_db_password, rd_db_name and mysql_db_hosts. Let me know how it goes. I might try using a seperate AWS server to see what needs to be tweaked.

**Comment by golimer** [comment]
everything works in production except user history 
after /usr/share/nginx/html/cake2 /usr/share/nginx/html/cake3 changing mysql credentials

**Comment by muffycompo** [comment]
@golimer sounds like an issue with the upstream project (RADIUSDesk) and not the installer. You can reach me via email muffycompoqm[at]gmail[dot]com so we can troubleshoot some more. There may be some hard coded references (to mysql on localhost) somewhere in the codebase of RD but we will have to find out.

**Comment by muffycompo** [comment]
@golimer, thank you the feedback once again, I have added the ability to use an external AWS RDS mySQL server by enabling an option in the variables file (roles/radiusdesk/vars/{Debian|RedHat}.yml) called enable_aws_rds_support. Changing this to true and supplying your RDS endpoint/host, and master username & password should point RADIUSDesk to the appropriate database references. I will work on a small documentation to others will benefit from this. Thank you again for point this requirement out.
