### ISSUE TITLE
radiusdesk-installer on ubuntu 18 lts - problems solved

### ISSUE THREAD

**Issue by stdkr** [muffycompo/radiusdesk-installer#50]
I installed radiusdesk successful on a fresh installed ubuntu 18 lts running as an virtual machine. while the installation I ran into some problems. here are the problems I ran into and how i solved them. perhaps someone finds this helpful. 

**Troubleshooting**

- [add php7.1 source to ubuntu ](https://tecadmin.net/install-php-7-on-ubuntu/)

		sudo apt-get install python-software-properties
		sudo add-apt-repository ppa:ondrej/php
		sudo apt-get update

- to install freeradius ppa, add followind dependency to Debian.yml

		vi roles/radiusdesk/vars/Debian.yml
			#Freeradius Packages (Ubuntu 14+)
			freeradius_pkgs:
			 - "libfreeradius3=3.0.16-ppa1*"

	- or install manually 

		apt install libfreeradius3=3.0.16-ppa1*
	- run ubuntu upgrade will install none ppa version of freeradius 
		- my solution: mark freeradius as hold to be ingored when doing an upgrade of ubuntu

			apt-mark hold libfreeradius3 freeradius freeradius-utils freeradius-mysql freeradius-ldap freeradius-krb5 freeradius-common
			apt-mark showhold
			apt upgrade
			apt list --upgradable

- depends on nmp and needs to be installed

		apt install nmp

- to run ansible automation for freeradius including chilli you need to install dynamic login page first
	- there is now guide to install dynamic login page include in the wiki
	- [a guide to install dynamic login page for radiusdesk with chilli](https://www.radiusdesk.com/old_wiki/getting_started/install_ubuntu_dynamic_login_pages)

Cheers

**Comment by muffycompo** [comment]
Thank you so much for that contribution @stdkr

**Comment by stdkr** [comment]
@muffycompo people still seem to have problems with the installer on ubuntu 18. could be an idea to include this in the wiki. since this issue is closed, people seem not to find this instructions.

**Comment by muffycompo** [comment]
Thanks once again @stdkr , I have added it to the FAQ section of the Wiki https://github.com/muffycompo/radiusdesk-installer/wiki/F.A.Q
