### ISSUE TITLE
Doesnt load login screen

### ISSUE THREAD

**Issue by skoenman** [muffycompo/radiusdesk-installer#7]
Hallo i have now tried loading on ubuntu 13 and 14 but it doesnt seem to install correctly. i doesnt load the login screen??? it shows the icon at the right bottom but nothing else...

**Comment by muffycompo** [comment]
Did it complete the installation successfully? Sounds Luke it missed some files.

**Comment by skoenman** [comment]
I also tried to install with script but get a bkank screen were login is suppose to be...what can one test for?

**Comment by muffycompo** [comment]
Thanks for the feedback and fixes @skoenman. Looking for some time to
update the script and check for more bugs. Your input will always be
welcome.

**Comment by muffycompo** [comment]
@nrahnemoon, I really appreciate your support, will let you know when I
update the script for beta testing...

**Comment by skoenman** [comment]
FOOUUNNDD IT /etc/nginx/sites-enabled/default theres a extra line in the file root with the html root in there and it seems to  
on this line 

```
# pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
#
location ~ \.php$ {
    fastcgi_split_path_info ^(.+\.php)(/.+)$;
    #       # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
    #
    #       # With php5-cgi alone:
    #       fastcgi_pass 127.0.0.1:9000;
    #       # With php5-fpm:
    fastcgi_pass unix:/var/run/php5-fpm.sock;
    fastcgi_index index.php;
    include fastcgi_params;
}
```

![capture](https://cloud.githubusercontent.com/assets/7958966/5381273/4096e6a6-80a8-11e4-9a45-b22446f33e13.JPG)

vim /etc/php5/fpm/pool.d/www.conf
(-- uncomment the line "listen.mode = 0666" by removing the semi-colon. save :wq!)
sudo service php5-fpm restart
sudo service nginx restart

thats it then its fixed...running on ubuntu 14.04

**Comment by muffycompo** [comment]
Ok. I am travelling for a conference on the 12th of December and back on
the 14th of December 2014. I might not have time to work on it immediately
but I have added it to my todo list so that I tackle it as soon as I combe
back.

**Comment by shankscoder** [comment]
Ok, on EC2 and Ubuntu, you need to ensure the system name is added to the hosts file so that localhost resolves correctly to the hostname. Otherwise you wont be able to connect to mysql via the CLI using localhost unless you explicitly define the host in the connect command:

    mysql -h localhost -u <username> -p

Fixing this and the other fixes mentioned in this thread got RD running for me on EC2 Ubuntu.

I'm having serious stability issues running this on Azure Ubuntu 14.04 systems. The installation fails to complete.

**Comment by muffycompo** [comment]
​Ok I will update the installer and investigate the Azure Ubuntu 14.04
issue.

**Comment by shankscoder** [comment]
Thanks @muffycompo Do let me know if I can help in anyway with the Azure testing.

**Comment by skoenman** [comment]
Muffycompo were you able to investigae maybe ??? just tried installing on ubuntu 14 and it still seems to add lines were its not suppose to???

**Comment by samansupriadi** [comment]
i dear i get same errors i doesnt load the login screen??? it shows the icon at the right bottom but nothing else... (freebsd 10.1)

error fear in log 
Call to undefined function mb_strtolower() in /usr/local/www/apache24/cakephp-2.6.7/lib/Cake/Utility/Inflector.php on line 483

**Comment by muffycompo** [comment]
It looks like a problem with the version of cakePHP on FreeBSD

**Comment by taylorbyte** [comment]
Hello, i have tried the following guide in order to set up RADIUSdesk on debian jessie with apache.
http://www.radiusdesk.com/getting_started/install_ubuntu_apache

i have completed to the bottom of that page ready to continue to the next step however when i test http://<ip address>/rd it shows a blank page with the logo in the bottom right corner. i have checked `/var/log/apache2/error.log` and no errors are present, i downloaded the exact version of `rd_cake` and `ext` but the `rd` svn could have changed since the guide was written. Not sure where else to look?

**Comment by muffycompo** [comment]
@taylorbyte you can try using your browsers dev tools like Chrome Dev Tools and inspect the Network Tab

**Comment by taylorbyte** [comment]
Thanks, like your videos btw. Firebug found: "NetworkError: 404 Not Found" for the following:

http://172.17.0.5/rd/ext/build/ext-all-rtl-debug.js?_dc=1453373781112"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/Component.js?_dc=1453373781112"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/container/ButtonGroup.js?_dc=1453373781112"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/form/field/HtmlEditor.js?_dc=1453373781112"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/grid/RowEditor.js?_dc=1453373781112"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/grid/column/RowNumberer.js?_dc=1453373781112"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/layout/component/Dock.js?_dc=1453373781112"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/menu/Menu.js?_dc=1453373781112"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/menu/Separator.js?_dc=1453373781112"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/panel/Panel.js?_dc=1453373781112"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/panel/Table.js?_dc=1453373781112"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/picker/Month.js?_dc=1453373781112"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/toolbar/Paging.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/resizer/Splitter.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-neptune/overrides/toolbar/Toolbar.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/Component.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/form/field/Checkbox.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/grid/column/Column.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/grid/column/RowNumberer.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/grid/plugin/RowExpander.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/list/TreeItem.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/menu/Item.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/menu/Menu.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/picker/Date.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/picker/Month.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/resizer/Splitter.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/selection/CheckboxModel.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/selection/SpreadsheetModel.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/classic/theme-triton/overrides/toolbar/Paging.js?_dc=1453373781113"
http://172.17.0.5/rd/ext/packages/charts/classic/overrides/AbstractChart.js?_dc=1453373781113"

I did some digging:

/var/www/rd/ext/builds/ext-all-rtl-debug.js (exists inside "builds" directory with an "s")
/var/www/rd/ext/packages/ext-theme-neptune/overrides/ (exists with files but wrong place)
/var/www/rd/ext/classic/theme-triton (does not exist)
/var/www/rd/ext/packages/charts/ (does not exist)

I did these steps: from [ubuntu apache](http://www.radiusdesk.com/getting_started/install_ubuntu_apache) guide

    svn checkout svn://svn.code.sf.net/p/radiusdesk/code/extjs/ ./
    unzip ext-4.2.1-gpl.zip -d /var/www/rd/
    mv /var/www/rd/ext-4.2.1.883 /var/www/rd/ext
    cp -R /var/www/rd/ext/examples/ux /var/www/rd/ext/src
    chown -R www-data. /var/www/rd/

and if the zip file hasn't changed or been tampered with those files should be all there, correct?

**Comment by muffycompo** [comment]
​You can check the nginx documentation as I can see some discrepancies and
I believe the nginx is more updated. Cheers!

**Comment by taylorbyte** [comment]
I noticed an extra file `ext-6-sencha_cmd.tar.gz` in the extjs svn checkout, the [ubuntu nginx](http://www.radiusdesk.com/getting_started/install_ubuntu_nginx) guide referred to it as a newer version and it works too. All i did was:

    rm -r /var/www/rd/ext/
    tar -xf ext-6-sencha_cmd.tar.gz -C /var/www/rd/
    chown -R www-data. /var/www/rd/

Thank you @muffycompo

**Comment by muffycompo** [comment]
You are welcome Brenton.

**Comment by doncoxy** [comment]
Hello ,
I have just completed the install on ubuntu 14.04 however i am no able to login to the system ,
error "not defined" Kindly help .

**Comment by dsantos3526** [comment]
hello,
i have problem after instal radius desk 
i can't login with username :root and password admin 
i have notice like this 

Failure
ajax communication failed


I use this introduction : http://www.radiusdesk.com/docuwiki/getting_started/install_ubuntu_nginx
what the problem yeah ?
thanks

**Comment by sithar** [comment]
Automatic installation went very well without any hiccups but I am not able to login using username :root and password admin, I get this error 
Failure
ajax communication failed

OS Ubuntu 16.04 Server

What could be wrong?

**Comment by muffycompo** [comment]
Could you post the content of /etc/php/7.0/fpm/pool.d/www.conf and /etc/nginx/sites-available/default. It sounds like nginx does not locate the php7.0-fpm socket file and so it can not properly communicate with php.

**Comment by sithar** [comment]
`/etc/php/7.0/fpm/pool.d/www.conf`

```
[www]
listen =  /var/run/php5-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0666
user = www-data
group = www-data
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
slowlog = /var/log/www-slow.log
php_admin_value[error_log] = /var/log/www-error.log
php_admin_flag[log_errors] = on
php_value[session.save_handler] = files
php_value[session.save_path] = /tmp

```
` /etc/nginx/sites-available/default`


```
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# http://wiki.nginx.org/Pitfalls
# http://wiki.nginx.org/QuickStart
# http://wiki.nginx.org/Configuration
#
# Generally, you will want to move this file somewhere, and start with a clean
# file but keep this around for reference. Or just disable in sites-enabled.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Default server configuration
#
server {
        listen 80 default_server;
        listen [::]:80 default_server;

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

        root /var/www/html;

        # Add index.php to the list if you are using PHP
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                try_files $uri $uri/ =404;
        }

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        #location ~ \.php$ {
        #       include snippets/fastcgi-php.conf;
        #
        #       # With php7.0-cgi alone:
        #       fastcgi_pass 127.0.0.1:9000;
        #       # With php7.0-fpm:
        #       fastcgi_pass unix:/run/php/php7.0-fpm.sock;
        #}

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #       deny all;
        #}
}


# Virtual Host configuration for example.com
#
# You can move that to a different file under sites-available/ and symlink that
# to sites-enabled/ to enable it.
#
#server {
#       listen 80;
#       listen [::]:80;
#
#       server_name example.com;
#
#       root /var/www/example.com;
#       index index.html;
#
#       location / {
#               try_files $uri $uri/ =404;
#       }
#}
```

**Comment by muffycompo** [comment]
It looks like the installer did not replace your `/etc/nginx/sites-available/default` config file. The content of the file should look like this:

```
#
# The default server
#
server {
    listen       80 default_server;
    server_name  _;

    #charset koi8-r;

    #access_log  logs/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.php index.html index.htm;
    }

    location = /favicon.ico {
      log_not_found off;
    }

    error_page  404  /404.html;
    location = /404.html {
        root   {{ nginx_webroot }};
    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # pass the PHP scripts to FastCGI server listening on UNIX Socket
    #
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        #       # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
        fastcgi_pass unix:/var/run/php7.0-fpm.sock;
        fastcgi_index index.php;
        include fastcgi.conf;
    }

	## RD-Installer Specific tweaks - Mfawa Alfred Onen
    location ~ ^/cake2/.+\.(jpg|jpeg|gif|png|ico|js|css)$ {
        rewrite ^/cake2/rd_cake/webroot/(.*)$ /cake2/rd_cake/webroot/$1 break;
        rewrite ^/cake2/rd_cake/(.*)$ /cake2/rd_cake/webroot/$1 break;
        access_log off;
        expires max;
        add_header Cache-Control public;
    } 

	location /cake2/rd_cake { 
		 rewrite ^/cake2/rd_cake/(.*)$ /cake2/rd_cake/webroot/$1 break; 
		 try_files $uri $uri/ /cake2/rd_cake/webroot/index.php?q=$uri&$args; 
	} 

    location /cake3/rd_cake {
       rewrite ^/cake3/rd_cake(.+)$ /cake3/rd_cake/webroot$1 break;
       try_files $uri $uri/ /cake3/rd_cake/index.php$is_args$args;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ /\.ht {
        deny  all;
    }
}
```

and the `listen = /var/run/php5-fpm.sock` should be `listen = /var/run/php7.0-fpm.sock` in `/etc/php/7.0/fpm/pool.d/www.conf`. After making the change, restart both services.

```
sudo systemctl restart php7.0-fpm
sudo systemctl restart nginx
```

**Comment by sithar** [comment]
Thanks it worked. But here's what I did. 
1. I moved the /etc/nginx/sites-enabled/default file to /etc/nginx/sites-available/, then symlinked it in the sites-enabled directory. (replaced the script with the one you provided above)
2. In your script above I changed root   /usr/share/nginx;   to root   /usr/share/nginx/html;

**Comment by muffycompo** [comment]
Alright, nice to hear it worked for you @sithar. Updated the script above also :)

**Comment by chimplinks** [comment]
I am also getting the same issue:

Failure
ajax communication failed

I have made the above mentioned changes however still get the issue.

please help

**Comment by rallep71** [comment]
same

I am also getting the same issue:

Failure
ajax communication failed

I have made the above mentioned changes however still get the issue.

please help

**Comment by rallep71** [comment]
2018/11/28 19:35:02 [crit] 1010#1010: *1 connect() to unix:/var/run/php/php7.0-fpm.sock failed (2: No such file or directory) while co$
2018/11/28 19:35:02 [error] 1010#1010: *1 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: 192.1$
2018/11/28 19:35:09 [crit] 1017#1017: *7 connect() to unix:/var/run/php/php7.0-fpm.sock failed (2: No such file or directory) while co$
2018/11/28 19:35:09 [error] 1017#1017: *7 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: 192.1$
2018/11/28 19:36:02 [crit] 1017#1017: *9 connect() to unix:/var/run/php/php7.0-fpm.sock failed (2: No such file or directory) while co$
2018/11/28 19:36:02 [error] 1017#1017: *9 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: 192.1$
2018/11/28 19:40:04 [crit] 1767#1767: *1 connect() to unix:/var/run/php/php7.0-fpm.sock failed (2: No such file or directory) while co$
2018/11/28 19:40:04 [error] 1767#1767: *1 open() "/usr/share/nginx/html/50x.html" failed (2: No such file or directory), client: 192.1$

**Comment by XPStef** [comment]
@chimplinks @rallep71 : I got the same problem like you guys and could fix it :)

First, you have to check the error log of nginx (/var/log/nginx/error.log). If there is an error mentioning it cannot find the php socket, you have to edit the config (of nginx and probably of php as well). The only step I had to do was for nginx.
Second, search for the phpX-fpm.sock file in /var/run . Depending on the version of php, it's named php5-fpm.sock or php7/php7.0-fpm.sock. Also have a look in the php folder (/var/run/php), maybe it's located in there. Third: If you've found the sock file, check the path to the socket in your php config under /etc/php/X/fpm/pool.d/www.conf (listen = ...). You may have to edit it (as I mentioned before, I could leave it, because it was the correct path to the socket file). Next, check the nginx config under /etc/nginx/sites-enabled/default. Edit  fastcgi_pass unix:... appropriately. This was the step I had to do, because the initial config stated to .../php/php7.0-fpm.sock.

As you can see  my config is a little bit fu**ed up, because I don't have php version 5 installed, but my socket file is called php5-fpm.sock . @all: I'm not an expert, so I don't know what's configured exactly  (and don't have the time to find out), but it works like that.

I tried it on Ubuntu 16.04 . Hope it can help someone :)
Cheers

/etc/php/7.0/fpm/pool.d/www.conf : 
```
[www]
listen =  /var/run/php5-fpm.sock
listen.owner = www-data
listen.group = www-data
listen.mode = 0666
user = www-data
group = www-data
pm = dynamic
pm.max_children = 50
pm.start_servers = 5
pm.min_spare_servers = 5
pm.max_spare_servers = 35
slowlog = /var/log/www-slow.log
php_admin_value[error_log] = /var/log/www-error.log
php_admin_flag[log_errors] = on
php_value[session.save_handler] = files
php_value[session.save_path] = /tmp
```

/etc/nginx/sites-enabled/default : 
```
#
# The default server
#
server {
    listen       80 default_server;
    server_name  _;

    #charset koi8-r;

    #access_log  logs/host.access.log  main;

    location / {
        root   /usr/share/nginx/html;
        index  index.php index.html index.htm;
    }

    location = /favicon.ico {
      log_not_found off;
    }

    error_page  404  /404.html;
    location = /404.html {
        root   /usr/share/nginx/html;
    }

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    # pass the PHP scripts to FastCGI server listening on UNIX Socket
    #
    location ~ \.php$ {
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        #       # NOTE: You should have "cgi.fix_pathinfo = 0;" in php.ini
                fastcgi_pass unix:/var/run/php5-fpm.sock;
                fastcgi_index index.php;
                include fastcgi.conf;
            }

        ## RD-Installer Specific tweaks - Mfawa Alfred Onen
    location ~ ^/cake2/.+\.(jpg|jpeg|gif|png|ico|js|css)$ {
        rewrite ^/cake2/rd_cake/webroot/(.*)$ /cake2/rd_cake/webroot/$1 break;
        rewrite ^/cake2/rd_cake/(.*)$ /cake2/rd_cake/webroot/$1 break;
        access_log off;
        expires max;
        add_header Cache-Control public;
    }

        location /cake2/rd_cake {
                 rewrite ^/cake2/rd_cake/(.*)$ /cake2/rd_cake/webroot/$1 break;
                 try_files $uri $uri/ /cake2/rd_cake/webroot/index.php?q=$uri&$args;
        }

    location /cake3/rd_cake {
       rewrite ^/cake3/rd_cake(.+)$ /cake3/rd_cake/webroot$1 break;
       try_files $uri $uri/ /cake3/rd_cake/index.php$is_args$args;
    }

    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ /\.ht {
        deny  all;
    }
}
```
