### ISSUE TITLE
Issue with Nginx Please help (Ubuntu 18.04):  TASK [radiusdesk : Installing Nginx (Ubuntu 14+)] ****************************** fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of state must be one of: absent, build-dep, fixed, latest, present, got: installed"}  PLAY RECAP ********************************************************************* localhost : ok=5 changed=1 unreachable=0 failed=1 skipped=3 rescued=0 ignored=0

### ISSUE THREAD

**Issue by MarujoNagoF** [muffycompo/radiusdesk-installer#73]
Please help (Ubuntu 18.04):

TASK [radiusdesk : Installing Nginx (Ubuntu 14+)] ******************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "value of state must be one of: absent, build-dep, fixed, latest, present, got: installed"}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=1    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

**Comment by MarujoNagoF** [comment]
I have fix it

**Comment by janky69** [comment]
> I have fix it

HOW?
