### ISSUE TITLE
nginx fails after system restart

### ISSUE THREAD

**Issue by shirishbandarkar** [muffycompo/radiusdesk-installer#9]
after installation is through when we restart the server nginx fails to start with error 
nginx: [emerg] open() "/etc/nginx/nginx.conf" failed (13: Permission denied)

I have freshly installed centos 6.6 minimal
installed radiusdesk installation script with default values
after installation configuration page availeble at http://ip/rd
but after server restart above error comes..
var/log/nginx/error.log has same eeror reported

Please inform where to search for error and solve the problem

**Comment by muffycompo** [comment]
It is a permissions issue, try changing the permission to 644 on the nginx.conf file and let us know if it fixed the issue
